In [3]:
import matplotlib.pyplot as plt 
import pandas as pd
import numpy as np

In [9]:
spotify_database = pd.read_csv(
    "spotify_global_trends_2026 - spotify_global_trends_final.csv", 
    index_col=0)
spotify_dtb_df = pd.DataFrame(spotify_database)

In [22]:
spotify_dtb_df

,artist_name,streams,stream_change,7day,genre,country,pos,days,viral_score,trend,popularity_category,longevity
track_name,,,,,,,,,,,,
SWIM,BTS,11273830,-3370522,25918182,K-Pop,KR,1,2,37192012,Falling,Trending,New
Body to Body,BTS,6815694,-4369341,18000729,K-Pop,KR,2,2,24816423,Falling,Trending,New
Babydoll,Dominic Fike,5733862,178968,36599831,Alternative Pop,Florida,3,119,42333693,Rising,Trending,Evergreen
Hooligan,BTS,5338608,-3396855,14074071,K-Pop,KR,4,2,19412679,Falling,Trending,New
FYA,BTS,5196767,-2873904,13267438,K-Pop,KR,5,2,18464205,Falling,Trending,New
...,...,...,...,...,...,...,...,...,...,...,...,...
The Chain - 2004 Remaster,Fleetwood Mac,1210598,-79537,8817306,Rock,GB,196,205,10027904,Falling,Average,Evergreen
Love On The Brain,Rihanna,1203160,-69820,7439269,Soul,US,197,352,8642429,Falling,Average,Evergreen
Sign of the Times,Harry Styles,1198929,-121566,3816744,Pop,England,198,331,5015673,Falling,Average,Evergreen
Sorry,Justin Bieber,1192146,-86760,7346804,Pop,CA,199,767,8538950,Falling,Average,Evergreen
Life Goes On,BTS,1191777,-76127,8979038,K-Pop,KR,200,207,10170815,Falling,Average,Evergreen

In [23]:
spotify_dtb_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 178 entries, SWIM to Life Goes On
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   artist_name          178 non-null    object
 1   streams              178 non-null    int64
 2   stream_change        178 non-null    int64
 3   7day                 178 non-null    int64
 4   genre                178 non-null    object
 5   country              178 non-null    object
 6   pos                  178 non-null    int64
 7   days                 178 non-null    int64
 8   viral_score          178 non-null    int64
 9   trend                178 non-null    object
 10  popularity_category  178 non-null    object
 11  longevity            178 non-null    object
dtypes: int64(6), object(6)
memory usage: 18.1+ KB

In [ ]:
spotify_dtb_df
spotify_dtb_df.rename(columns={'7day': 'streams_7day'})
spotify_dtb_df.loc([""]))

,artist_name,streams,stream_change,streams_7day,genre,country,pos,days,viral_score,trend,popularity_category,longevity
track_name,,,,,,,,,,,,
SWIM,BTS,11273830,-3370522,25918182,K-Pop,KR,1,2,37192012,Falling,Trending,New
Body to Body,BTS,6815694,-4369341,18000729,K-Pop,KR,2,2,24816423,Falling,Trending,New
Babydoll,Dominic Fike,5733862,178968,36599831,Alternative Pop,Florida,3,119,42333693,Rising,Trending,Evergreen
Hooligan,BTS,5338608,-3396855,14074071,K-Pop,KR,4,2,19412679,Falling,Trending,New
FYA,BTS,5196767,-2873904,13267438,K-Pop,KR,5,2,18464205,Falling,Trending,New
...,...,...,...,...,...,...,...,...,...,...,...,...
The Chain - 2004 Remaster,Fleetwood Mac,1210598,-79537,8817306,Rock,GB,196,205,10027904,Falling,Average,Evergreen
Love On The Brain,Rihanna,1203160,-69820,7439269,Soul,US,197,352,8642429,Falling,Average,Evergreen
Sign of the Times,Harry Styles,1198929,-121566,3816744,Pop,England,198,331,5015673,Falling,Average,Evergreen
Sorry,Justin Bieber,1192146,-86760,7346804,Pop,CA,199,767,8538950,Falling,Average,Evergreen
Life Goes On,BTS,1191777,-76127,8979038,K-Pop,KR,200,207,10170815,Falling,Average,Evergreen