In [1]:
import matplotlib.pyplot as plt 
import pandas as pd
import numpy as np

In [2]:
spotify_database = pd.read_csv(
    "spotify_global_trends_2026 - spotify_global_trends_final.csv", 
    index_col=0)
spotify_dtb_df = pd.DataFrame(spotify_database)

In [3]:
spotify_dtb_df

,artist_name,streams,stream_change,7day,genre,country,pos,days,viral_score,trend,popularity_category,longevity
track_name,,,,,,,,,,,,
SWIM,BTS,11273830,-3370522,25918182,K-Pop,KR,1,2,37192012,Falling,Trending,New
Body to Body,BTS,6815694,-4369341,18000729,K-Pop,KR,2,2,24816423,Falling,Trending,New
Babydoll,Dominic Fike,5733862,178968,36599831,Alternative Pop,Florida,3,119,42333693,Rising,Trending,Evergreen
Hooligan,BTS,5338608,-3396855,14074071,K-Pop,KR,4,2,19412679,Falling,Trending,New
FYA,BTS,5196767,-2873904,13267438,K-Pop,KR,5,2,18464205,Falling,Trending,New
...,...,...,...,...,...,...,...,...,...,...,...,...
The Chain - 2004 Remaster,Fleetwood Mac,1210598,-79537,8817306,Rock,GB,196,205,10027904,Falling,Average,Evergreen
Love On The Brain,Rihanna,1203160,-69820,7439269,Soul,US,197,352,8642429,Falling,Average,Evergreen
Sign of the Times,Harry Styles,1198929,-121566,3816744,Pop,England,198,331,5015673,Falling,Average,Evergreen
Sorry,Justin Bieber,1192146,-86760,7346804,Pop,CA,199,767,8538950,Falling,Average,Evergreen
Life Goes On,BTS,1191777,-76127,8979038,K-Pop,KR,200,207,10170815,Falling,Average,Evergreen

In [4]:
spotify_dtb_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 178 entries, SWIM to Life Goes On
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   artist_name          178 non-null    object
 1   streams              178 non-null    int64
 2   stream_change        178 non-null    int64
 3   7day                 178 non-null    int64
 4   genre                178 non-null    object
 5   country              178 non-null    object
 6   pos                  178 non-null    int64
 7   days                 178 non-null    int64
 8   viral_score          178 non-null    int64
 9   trend                178 non-null    object
 10  popularity_category  178 non-null    object
 11  longevity            178 non-null    object
dtypes: int64(6), object(6)
memory usage: 18.1+ KB

In [5]:
spotify_dtb_df.loc['Babydoll', 'country'] = "US"
spotify_dtb_df.loc['Sign of the Times', 'country'] = "UK"
spotify_dtb_df

,artist_name,streams,stream_change,7day,genre,country,pos,days,viral_score,trend,popularity_category,longevity
track_name,,,,,,,,,,,,
SWIM,BTS,11273830,-3370522,25918182,K-Pop,KR,1,2,37192012,Falling,Trending,New
Body to Body,BTS,6815694,-4369341,18000729,K-Pop,KR,2,2,24816423,Falling,Trending,New
Babydoll,Dominic Fike,5733862,178968,36599831,Alternative Pop,US,3,119,42333693,Rising,Trending,Evergreen
Hooligan,BTS,5338608,-3396855,14074071,K-Pop,KR,4,2,19412679,Falling,Trending,New
FYA,BTS,5196767,-2873904,13267438,K-Pop,KR,5,2,18464205,Falling,Trending,New
...,...,...,...,...,...,...,...,...,...,...,...,...
The Chain - 2004 Remaster,Fleetwood Mac,1210598,-79537,8817306,Rock,GB,196,205,10027904,Falling,Average,Evergreen
Love On The Brain,Rihanna,1203160,-69820,7439269,Soul,US,197,352,8642429,Falling,Average,Evergreen
Sign of the Times,Harry Styles,1198929,-121566,3816744,Pop,UK,198,331,5015673,Falling,Average,Evergreen
Sorry,Justin Bieber,1192146,-86760,7346804,Pop,CA,199,767,8538950,Falling,Average,Evergreen
Life Goes On,BTS,1191777,-76127,8979038,K-Pop,KR,200,207,10170815,Falling,Average,Evergreen

In [6]:
spotify_dtb_df = spotify_dtb_df.rename(columns={
    "artist_name" : "artist",
    "pos" : "position",
    "days" : "days_on_chart",
    '7day': 'streams_7day'
})

spotify_dtb_df

,artist,streams,stream_change,streams_7day,genre,country,position,days_on_chart,viral_score,trend,popularity_category,longevity
track_name,,,,,,,,,,,,
SWIM,BTS,11273830,-3370522,25918182,K-Pop,KR,1,2,37192012,Falling,Trending,New
Body to Body,BTS,6815694,-4369341,18000729,K-Pop,KR,2,2,24816423,Falling,Trending,New
Babydoll,Dominic Fike,5733862,178968,36599831,Alternative Pop,US,3,119,42333693,Rising,Trending,Evergreen
Hooligan,BTS,5338608,-3396855,14074071,K-Pop,KR,4,2,19412679,Falling,Trending,New
FYA,BTS,5196767,-2873904,13267438,K-Pop,KR,5,2,18464205,Falling,Trending,New
...,...,...,...,...,...,...,...,...,...,...,...,...
The Chain - 2004 Remaster,Fleetwood Mac,1210598,-79537,8817306,Rock,GB,196,205,10027904,Falling,Average,Evergreen
Love On The Brain,Rihanna,1203160,-69820,7439269,Soul,US,197,352,8642429,Falling,Average,Evergreen
Sign of the Times,Harry Styles,1198929,-121566,3816744,Pop,UK,198,331,5015673,Falling,Average,Evergreen
Sorry,Justin Bieber,1192146,-86760,7346804,Pop,CA,199,767,8538950,Falling,Average,Evergreen
Life Goes On,BTS,1191777,-76127,8979038,K-Pop,KR,200,207,10170815,Falling,Average,Evergreen

In [7]:
spotify_dtb_df.iloc[6:51]
spotify_dtb_df.iloc[6:7, 5:6] = "UK"
spotify_dtb_df.iloc[6:51]

,artist,streams,stream_change,streams_7day,genre,country,position,days_on_chart,viral_score,trend,popularity_category,longevity
track_name,,,,,,,,,,,,
Stateside + Zara Larsson (w/ Zara Larsson),PinkPantheress,4738329,-235112,34238168,Uk Garage,UK,7,74,38976497,Falling,Average,Stable Hit
Aliens,BTS,4718569,-3036604,12473742,K-Pop,KR,8,2,17192311,Falling,Average,New
2,BTS,4573989,-2809104,11957082,K-Pop,KR,9,2,16531071,Falling,Average,New
Like Animals,BTS,4567309,-2259887,11394505,K-Pop,KR,10,2,15961814,Falling,Average,New
Merry Go Round,BTS,4490039,-2740868,11720946,K-Pop,KR,11,2,16210985,Falling,Average,New
they don’t know ’bout us,BTS,4423675,-2305775,11153125,K-Pop,KR,12,2,15576800,Falling,Average,New
Man I Need,Olivia Dean,4300853,-86237,28683798,Pop,US,13,214,32984651,Falling,Average,Evergreen
DtMF,Bad Bunny,4274742,-111657,29551375,Pop,PR,14,441,33826117,Falling,Average,Evergreen
End of Beginning,Djo,4108838,51706,27783861,Synth-Pop,US,15,764,31892699,Rising,Average,Evergreen
Risk It All,Bruno Mars,4007478,-499146,31739152,Offizielle Charts,US,16,23,35746630,Falling,Average,New
One More Night,BTS,3979999,-2153273,10113271,K-Pop,KR,17,2,14093270,Falling,Average,New
So Easy (To Fall In Love),Olivia Dean,3932082,33687,27406397,Pop,US,18,176,31338479,Rising,Average,Evergreen
Please,BTS,3897341,-2024958,9819640,K-Pop,KR,19,2,13716981,Falling,Average,New
Raindance (w/ Tems),Dave,3876044,-197505,25945780,Rap,US,20,109,29821824,Falling,Average,Evergreen
No. 29,BTS,3769141,-2733812,10272094,K-Pop,KR,21,2,14041235,Falling,Average,New
Into the Sun,BTS,3766459,-1959266,9492184,K-Pop,KR,22,2,13258643,Falling,Average,New
The Fate of Ophelia,Taylor Swift,3721332,-164240,26075129,Pop,US,23,170,29796461,Falling,Average,Evergreen
back to friends,sombr,3583316,-131585,25787563,Indie Pop,US,25,369,29370879,Falling,Average,Evergreen
BAILE INoLVIDABLE,Bad Bunny,3344867,-44475,22663387,Reggaeton,PR,26,441,26008254,Falling,Average,Evergreen
Lush Life,Zara Larsson,3341957,-21457,21857968,Pop,SE,27,761,25199925,Falling,Average,Evergreen
WHERE IS MY HUSBAND!,RAYE,3241010,5314,22068930,Pop,GB,28,184,25309940,Rising,Average,Evergreen
NUEVAYoL,Bad Bunny,3221298,-80099,21951925,Reggaeton,PR,29,441,25173223,Falling,Average,Evergreen
American Girls,Harry Styles,3101460,-420059,24771218,Rock,England,31,16,27872678,Falling,Average,New
iloveitiloveitiloveit,Bella Kay,2978129,-293545,22515039,Billboard Hot 100,US,32,30,25493168,Falling,Average,New
I Just Might,Bruno Mars,2860193,-16107,19846361,Pop,US,33,72,22706554,Falling,Average,Stable Hit
Iris,The Goo Goo Dolls,2776320,-126309,19907609,Alternative Rock,US,34,919,22683929,Falling,Average,Evergreen
Die With A Smile (w/ Bruno Mars),Lady Gaga,2691880,-142292,19325340,Pop,US,35,583,22017220,Falling,Average,Evergreen
Manchild,Sabrina Carpenter,2649376,-38989,17388953,Pop,US,36,289,20038329,Falling,Average,Evergreen
Tití Me Preguntó,Bad Bunny,2649180,-7253,17660827,Reggaeton,PR,37,483,20310007,Falling,Average,Evergreen
Love Me Not,Ravyn Lenae,2547681,-24120,17684406,Pop,US,38,368,20232087,Falling,Average,Evergreen
EoO,Bad Bunny,2542905,-123890,17968199,Billboard Hot 100,PR,39,437,20511104,Falling,Average,Evergreen
White Keys,Dominic Fike,2531236,-178737,17360808,Offizielle Charts,Florida,40,28,19892044,Falling,Average,New
BIRDS OF A FEATHER,Billie Eilish,2529075,24180,17056445,Alternative Pop,US,41,674,19585520,Rising,Average,Evergreen
Die On This Hill,SIENNA SPIRO,2398309,-322885,19212395,Pop,GB,43,102,21610704,Falling,Average,Evergreen
Every Breath You Take,The Police,2367833,25446,16070168,New Wave,GB,44,1619,18438001,Rising,Average,Evergreen
Dracula - JENNIE Remix (w/ JENNIE),Tame Impala,2332341,-89323,15767565,Psychedelic Rock,AU,45,36,18099906,Falling,Average,Stable Hit
12 to 12,sombr,2260402,-86182,15853606,Indie Pop,US,46,236,18114008,Falling,Average,Evergreen
Mr. Brightside,The Killers,2220784,-28156,14355698,Rock,GB,47,1682,16576482,Falling,Average,Evergreen
Espresso,Sabrina Carpenter,2213750,90339,13566149,Pop,US,48,709,15779899,Rising,Average,Evergreen
Choosin' Texas,Ella Langley,2169091,10331,13900513,Country,US,49,80,16069604,Rising,Average,Stable Hit
I Thought I Saw Your Face Today,She & Him,2155500,-138406,15647967,Indie Pop,US,50,104,17803467,Falling,Average,Evergreen
(When You Gonna) Give It Up to Me (w/ Keyshia Cole),Sean Paul,2154338,-112939,14951009,Dancehall,JM,51,65,17105347,Falling,Average,Stable Hit
Homewrecker,sombr,2139700,-220893,15402927,Indie Pop,US,52,44,17542627,Falling,Average,Stable Hit
Sailor Song,Gigi Perez,2107410,-121996,16461691,Electronic,IT,53,581,18569101,Falling,Average,Evergreen
Beautiful Things,Benson Boone,2090231,129461,13021976,Pop,US,54,793,15112207,Rising,Average,Evergreen

In [8]:
spotify_dtb_df.loc['White Keys', 'country'] = "US"
spotify_dtb_df.loc['American Girls', 'country'] = "US"
spotify_dtb_df.loc['iloveitiloveitiloveit', 'genre'] = "Indie Pop"
spotify_dtb_df.loc['EoO', 'genre'] = "Reggaeton"
spotify_dtb_df.loc['Risk It All', 'genre'] = "Pop"
spotify_dtb_df.loc['White Keys', 'genre'] = "Indie Pop"
spotify_dtb_df.iloc[6:51]

,artist,streams,stream_change,streams_7day,genre,country,position,days_on_chart,viral_score,trend,popularity_category,longevity
track_name,,,,,,,,,,,,
Stateside + Zara Larsson (w/ Zara Larsson),PinkPantheress,4738329,-235112,34238168,Uk Garage,UK,7,74,38976497,Falling,Average,Stable Hit
Aliens,BTS,4718569,-3036604,12473742,K-Pop,KR,8,2,17192311,Falling,Average,New
2,BTS,4573989,-2809104,11957082,K-Pop,KR,9,2,16531071,Falling,Average,New
Like Animals,BTS,4567309,-2259887,11394505,K-Pop,KR,10,2,15961814,Falling,Average,New
Merry Go Round,BTS,4490039,-2740868,11720946,K-Pop,KR,11,2,16210985,Falling,Average,New
they don’t know ’bout us,BTS,4423675,-2305775,11153125,K-Pop,KR,12,2,15576800,Falling,Average,New
Man I Need,Olivia Dean,4300853,-86237,28683798,Pop,US,13,214,32984651,Falling,Average,Evergreen
DtMF,Bad Bunny,4274742,-111657,29551375,Pop,PR,14,441,33826117,Falling,Average,Evergreen
End of Beginning,Djo,4108838,51706,27783861,Synth-Pop,US,15,764,31892699,Rising,Average,Evergreen
Risk It All,Bruno Mars,4007478,-499146,31739152,Pop,US,16,23,35746630,Falling,Average,New
One More Night,BTS,3979999,-2153273,10113271,K-Pop,KR,17,2,14093270,Falling,Average,New
So Easy (To Fall In Love),Olivia Dean,3932082,33687,27406397,Pop,US,18,176,31338479,Rising,Average,Evergreen
Please,BTS,3897341,-2024958,9819640,K-Pop,KR,19,2,13716981,Falling,Average,New
Raindance (w/ Tems),Dave,3876044,-197505,25945780,Rap,US,20,109,29821824,Falling,Average,Evergreen
No. 29,BTS,3769141,-2733812,10272094,K-Pop,KR,21,2,14041235,Falling,Average,New
Into the Sun,BTS,3766459,-1959266,9492184,K-Pop,KR,22,2,13258643,Falling,Average,New
The Fate of Ophelia,Taylor Swift,3721332,-164240,26075129,Pop,US,23,170,29796461,Falling,Average,Evergreen
back to friends,sombr,3583316,-131585,25787563,Indie Pop,US,25,369,29370879,Falling,Average,Evergreen
BAILE INoLVIDABLE,Bad Bunny,3344867,-44475,22663387,Reggaeton,PR,26,441,26008254,Falling,Average,Evergreen
Lush Life,Zara Larsson,3341957,-21457,21857968,Pop,SE,27,761,25199925,Falling,Average,Evergreen
WHERE IS MY HUSBAND!,RAYE,3241010,5314,22068930,Pop,GB,28,184,25309940,Rising,Average,Evergreen
NUEVAYoL,Bad Bunny,3221298,-80099,21951925,Reggaeton,PR,29,441,25173223,Falling,Average,Evergreen
American Girls,Harry Styles,3101460,-420059,24771218,Rock,US,31,16,27872678,Falling,Average,New
iloveitiloveitiloveit,Bella Kay,2978129,-293545,22515039,Indie Pop,US,32,30,25493168,Falling,Average,New
I Just Might,Bruno Mars,2860193,-16107,19846361,Pop,US,33,72,22706554,Falling,Average,Stable Hit
Iris,The Goo Goo Dolls,2776320,-126309,19907609,Alternative Rock,US,34,919,22683929,Falling,Average,Evergreen
Die With A Smile (w/ Bruno Mars),Lady Gaga,2691880,-142292,19325340,Pop,US,35,583,22017220,Falling,Average,Evergreen
Manchild,Sabrina Carpenter,2649376,-38989,17388953,Pop,US,36,289,20038329,Falling,Average,Evergreen
Tití Me Preguntó,Bad Bunny,2649180,-7253,17660827,Reggaeton,PR,37,483,20310007,Falling,Average,Evergreen
Love Me Not,Ravyn Lenae,2547681,-24120,17684406,Pop,US,38,368,20232087,Falling,Average,Evergreen
EoO,Bad Bunny,2542905,-123890,17968199,Reggaeton,PR,39,437,20511104,Falling,Average,Evergreen
White Keys,Dominic Fike,2531236,-178737,17360808,Indie Pop,US,40,28,19892044,Falling,Average,New
BIRDS OF A FEATHER,Billie Eilish,2529075,24180,17056445,Alternative Pop,US,41,674,19585520,Rising,Average,Evergreen
Die On This Hill,SIENNA SPIRO,2398309,-322885,19212395,Pop,GB,43,102,21610704,Falling,Average,Evergreen
Every Breath You Take,The Police,2367833,25446,16070168,New Wave,GB,44,1619,18438001,Rising,Average,Evergreen
Dracula - JENNIE Remix (w/ JENNIE),Tame Impala,2332341,-89323,15767565,Psychedelic Rock,AU,45,36,18099906,Falling,Average,Stable Hit
12 to 12,sombr,2260402,-86182,15853606,Indie Pop,US,46,236,18114008,Falling,Average,Evergreen
Mr. Brightside,The Killers,2220784,-28156,14355698,Rock,GB,47,1682,16576482,Falling,Average,Evergreen
Espresso,Sabrina Carpenter,2213750,90339,13566149,Pop,US,48,709,15779899,Rising,Average,Evergreen
Choosin' Texas,Ella Langley,2169091,10331,13900513,Country,US,49,80,16069604,Rising,Average,Stable Hit
I Thought I Saw Your Face Today,She & Him,2155500,-138406,15647967,Indie Pop,US,50,104,17803467,Falling,Average,Evergreen
(When You Gonna) Give It Up to Me (w/ Keyshia Cole),Sean Paul,2154338,-112939,14951009,Dancehall,JM,51,65,17105347,Falling,Average,Stable Hit
Homewrecker,sombr,2139700,-220893,15402927,Indie Pop,US,52,44,17542627,Falling,Average,Stable Hit
Sailor Song,Gigi Perez,2107410,-121996,16461691,Electronic,IT,53,581,18569101,Falling,Average,Evergreen
Beautiful Things,Benson Boone,2090231,129461,13021976,Pop,US,54,793,15112207,Rising,Average,Evergreen

In [9]:
spotify_dtb_df[51:101]
spotify_dtb_df.loc[spotify_dtb_df['country'] == 'England', 'country'] = 'UK'

mexico_cities = ['Culiacán', 'Monterrey']
spotify_dtb_df.loc[spotify_dtb_df['country'].isin(mexico_cities), 'country'] = 'MX'
spotify_dtb_df.loc['E85', 'genre'] = 'Trap'

great_britain = ['UK', 'England']
spotify_dtb_df.loc[spotify_dtb_df['country'].isin(great_britain), 'country'] = "GB"

spotify_dtb_df.loc['FEVER DREAM', 'genre'] = "Pop"
spotify_dtb_df.loc['Gabriela', 'genre'] = "Pop"
spotify_dtb_df.loc['La Plena - W Sound 05 (w/ Beéle, Ovy On The Drums)', 'genre'] = "Reggaeton"
spotify_dtb_df.loc['Marlboro Rojo', 'genre'] = 'Regional Mexican'
spotify_dtb_df.loc['Alex Warren', 'genre'] = 'Pop'
spotify_dtb_df.loc['The Visitor', 'artist'] = 'Sienna Spiro'
spotify_dtb_df.loc['Si Antes Te Hubiera Conocido', 'artist'] = 'Karol G'
spotify_dtb_df[51:101]

,artist,streams,stream_change,streams_7day,genre,country,position,days_on_chart,viral_score,trend,popularity_category,longevity
track_name,,,,,,,,,,,,
Sweater Weather,The Neighbourhood,2068795.0,-177998.0,15845100.0,Rock,GB,56.0,2120.0,17913895.0,Falling,Average,Evergreen
"One Dance (w/ Wizkid, Kyla)",Drake,2035423.0,-105895.0,13481976.0,Hip Hop,CA,57.0,2135.0,15517399.0,Falling,Average,Evergreen
Rein Me In (w/ Olivia Dean),Sam Fender,2020602.0,-34643.0,12610414.0,Rock,GB,58.0,23.0,14631016.0,Falling,Average,New
Creep,Radiohead,2011657.0,-91449.0,14176633.0,Rock,GB,59.0,842.0,16188290.0,Falling,Average,Evergreen
Opalite,Taylor Swift,1992549.0,-70008.0,14093798.0,Pop,US,60.0,170.0,16086347.0,Falling,Average,Evergreen
FEVER DREAM,Alex Warren,1992250.0,-130117.0,13935046.0,Pop,GB,61.0,23.0,15927296.0,Falling,Average,New
dopamina (w/ Tito Double P),Peso Pluma,1952764.0,66159.0,12629601.0,Regional Mexicano,MX,62.0,86.0,14582365.0,Rising,Average,Stable Hit
E85,Don Toliver,1948495.0,-127853.0,13479304.0,Trap,US,63.0,51.0,15427799.0,Falling,Average,Stable Hit
That's What I Like,Bruno Mars,1912383.0,-142486.0,12699826.0,Pop,US,65.0,1254.0,14612209.0,Falling,Average,Evergreen
Dracula,Tame Impala,1906471.0,-84531.0,13354497.0,Dance-Pop,AU,66.0,138.0,15260968.0,Falling,Average,Evergreen
Dreams - 2004 Remaster,Fleetwood Mac,1894536.0,109844.0,11986886.0,Rock,GB,67.0,1004.0,13881422.0,Rising,Average,Evergreen
Gabriela,KATSEYE,1850006.0,60664.0,12468922.0,Pop,US,68.0,275.0,14318928.0,Rising,Average,Evergreen
Yellow,Coldplay,1828666.0,-99526.0,12862160.0,Alternative Rock,GB,69.0,1909.0,14690826.0,Falling,Average,Evergreen
Locked out of Heaven,Bruno Mars,1827015.0,-180903.0,13448378.0,Pop,US,70.0,1548.0,15275393.0,Falling,Average,Evergreen
I Wanna Be Yours,Arctic Monkeys,1825413.0,-80003.0,13563046.0,Indie Rock,GB,71.0,1354.0,15388459.0,Falling,Average,Evergreen
Who,Jimin,1807214.0,176731.0,11524586.0,Contemporary R&B,KR,72.0,611.0,13331800.0,Rising,Average,Evergreen
VOY A LLeVARTE PA PR,Bad Bunny,1780848.0,-133648.0,12359622.0,Reggaeton,PR,74.0,375.0,14140470.0,Falling,Average,Evergreen
daño (w/ Tito Double P),Peso Pluma,1780764.0,34375.0,11510694.0,Regional Mexicano,MX,75.0,86.0,13291458.0,Rising,Average,Stable Hit
Starboy (w/ Daft Punk),The Weeknd,1761445.0,-119116.0,12541479.0,R&B,CA,76.0,2095.0,14302924.0,Falling,Average,Evergreen
Lose Control,Teddy Swims,1737868.0,29374.0,11380332.0,Pop,US,77.0,856.0,13118200.0,Rising,Average,Evergreen
Riptide,Vance Joy,1737857.0,-5537.0,11544093.0,Rock,AU,78.0,2586.0,13281950.0,Falling,Average,Evergreen
WILDFLOWER,Billie Eilish,1730195.0,-201850.0,13900491.0,Alternative Pop,US,79.0,674.0,15630686.0,Falling,Average,Evergreen
LA CANCIÓN (w/ Bad Bunny),J Balvin,1708412.0,3072.0,11498926.0,Electronic,CO,80.0,988.0,13207338.0,Rising,Average,Evergreen
Qué Pasaría... (w/ Bad Bunny),Rauw Alejandro,1674168.0,25719.0,11406360.0,Reggaeton,PR,82.0,427.0,13080528.0,Rising,Average,Evergreen
Feel Good Inc,Gorillaz,1669648.0,-99808.0,11921501.0,Electronic,GB,83.0,443.0,13591149.0,Falling,Average,Evergreen
All The Stars (w/ SZA),Kendrick Lamar,1665602.0,-10997.0,11456499.0,Hip Hop,US,84.0,1016.0,13122101.0,Falling,Average,Evergreen
See You Again (w/ Kali Uchis),"Tyler, The Creator",1662229.0,73090.0,10586720.0,Hip Hop,US,85.0,1066.0,12248949.0,Rising,Average,Evergreen
In the End,Linkin Park,1647656.0,-111701.0,11401354.0,Nu Metal,US,86.0,1012.0,13049010.0,Falling,Average,Evergreen
"One Of The Girls (w/ JENNIE, Lily-Rose Depp)",The Weeknd,1643774.0,-137154.0,12741548.0,R&B,CA,87.0,896.0,14385322.0,Falling,Average,Evergreen
Danza Kuduro (w/ Lucenzo),Don Omar,1643700.0,-105775.0,10737763.0,Reggaeton,PR,88.0,802.0,12381463.0,Falling,Average,Evergreen
Aperture,Harry Styles,1643576.0,-159524.0,13195579.0,Pop,GB,89.0,58.0,14839155.0,Falling,Average,Stable Hit
"La Plena - W Sound 05 (w/ Beéle, Ovy On The Drums)",W Sound,1639753.0,-17075.0,10668572.0,Reggaeton,JP,90.0,389.0,12308325.0,Falling,Average,Evergreen
"LA VILLA (w/ Kapo, Gangsta)",Ryan Castro,1634806.0,64909.0,10801896.0,Rock,US,91.0,75.0,12436702.0,Rising,Average,Stable Hit
"Good Luck, Babe!",Chappell Roan,1621060.0,15852.0,10803226.0,Pop,US,92.0,710.0,12424286.0,Rising,Average,Evergreen
Viva La Vida,Coldplay,1610233.0,106290.0,10117917.0,Alternative Rock,GB,93.0,1329.0,11728150.0,Rising,Average,Evergreen
As It Was,Harry Styles,1608775.0,-150504.0,11660629.0,Pop,GB,94.0,1401.0,13269404.0,Falling,Average,Evergreen
We Are The People,Empire Of The Sun,1594097.0,-30037.0,11149329.0,Electronic,AU,95.0,242.0,12743426.0,Falling,Average,Evergreen
The Less I Know The Better,Tame Impala,1593781.0,-51333.0,10870662.0,Psychedelic Rock,AU,96.0,510.0,12464443.0,Falling,Average,Evergreen
505,Arctic Monkeys,1587695.0,-113645.0,11653237.0,Indie Rock,GB,97.0,1537.0,13240932.0,Falling,Average,Evergreen
Seven (w/ Latto),Jung Kook,1580746.0,-80854.0,11202875.0,Pop,KR,98.0,981.0,12783621.0,Falling,Average,Evergreen
Marlboro Rojo,Fuerza Regida,1564019.0,112870.0,10014833.0,Regional Mexican,MX,99.0,317.0,11578852.0,Rising,Average,Evergreen
Todo Lo Fue,Lenin Ramírez,1563733.0,90601.0,10043908.0,Regional Mexicano,MX,100.0,58.0,11607641.0,Rising,Average,Stable Hit
The Visitor,Sienna Spiro,1558344.0,-296012.0,12044907.0,Pop Soul,GB,101.0,9.0,13603251.0,Falling,Average,New
Billie Jean,Michael Jackson,1551069.0,20972.0,9991848.0,Pop,US,102.0,363.0,11542917.0,Rising,Average,Evergreen
Si Antes Te Hubiera Conocido,Karol G,1540953.0,46742.0,9623813.0,Reggaeton,CO,103.0,583.0,11164766.0,Rising,Average,Evergreen
Pvta Luna,Neton Vega,1537690.0,56324.0,10293259.0,Regional Mexicano,MX,104.0,127.0,11830949.0,Rising,Average,Evergreen
Ya Borracho,Herencia De Grandes,1536251.0,49704.0,9999127.0,Regional Mexicano,MX,105.0,122.0,11535378.0,Rising,Average,Evergreen
undressed,sombr,1535615.0,-88400.0,10972970.0,Indie Pop,US,106.0,358.0,12508585.0,Falling,Average,Evergreen
Shape of You,Ed Sheeran,1532739.0,-41473.0,10263688.0,Pop,GB,107.0,2815.0,11796427.0,Falling,Average,Evergreen
That’s So True,Gracie Abrams,1526228.0,-51917.0,10719195.0,Folk Pop,US,108.0,519.0,12245423.0,Falling,Average,Evergreen

In [20]:
pd.set_option('display.max_rows', 500)
country_df = spotify_dtb_df[['genre']]
country_df

                                                                     genre
track_name
SWIM                                                                 K-Pop
Body to Body                                                         K-Pop
Babydoll                                                   Alternative Pop
Hooligan                                                             K-Pop
FYA                                                                  K-Pop
NORMAL                                                               K-Pop
Stateside + Zara Larsson (w/ Zara Larsson)                       Uk Garage
Aliens                                                               K-Pop
2                                                                    K-Pop
Like Animals                                                         K-Pop
Merry Go Round                                                       K-Pop
they don’t know ’bout us                                             K-Pop
Man I Need                                                             Pop
DtMF                                                                   Pop
End of Beginning                                                 Synth-Pop
Risk It All                                                            Pop
One More Night                                                       K-Pop
So Easy (To Fall In Love)                                              Pop
Please                                                               K-Pop
Raindance (w/ Tems)                                                    Rap
No. 29                                                               K-Pop
Into the Sun                                                         K-Pop
The Fate of Ophelia                                                    Pop
back to friends                                                  Indie Pop
BAILE INoLVIDABLE                                                Reggaeton
Lush Life                                                              Pop
WHERE IS MY HUSBAND!                                                   Pop
NUEVAYoL                                                         Reggaeton
American Girls                                                        Rock
iloveitiloveitiloveit                                            Indie Pop
I Just Might                                                           Pop
Iris                                                      Alternative Rock
Die With A Smile (w/ Bruno Mars)                                       Pop
Manchild                                                               Pop
Tití Me Preguntó                                                 Reggaeton
Love Me Not                                                            Pop
EoO                                                              Reggaeton
White Keys                                                       Indie Pop
BIRDS OF A FEATHER                                         Alternative Pop
Die On This Hill                                                       Pop
Every Breath You Take                                             New Wave
Dracula - JENNIE Remix (w/ JENNIE)                        Psychedelic Rock
12 to 12                                                         Indie Pop
Mr. Brightside                                                        Rock
Espresso                                                               Pop
Choosin' Texas                                                     Country
I Thought I Saw Your Face Today                                  Indie Pop
(When You Gonna) Give It Up to Me (w/ Keyshia C...               Dancehall
Homewrecker                                                      Indie Pop
Sailor Song                                                     Electronic
Beautiful Things                                                       Pop
Sweater Weather                                                       Rock
One Dance (w/ Wizkid, Kyla)                                        Hip Hop
Rein Me In (w/ Olivia Dean)                                           Rock
Creep                                                                 Rock
Opalite                                                                Pop
FEVER DREAM                                                            Pop
dopamina (w/ Tito Double P)                              Regional Mexicano
E85                                                                   Trap
That's What I Like                                                     Pop
Dracula                                                          Dance-Pop
Dreams - 2004 Remaster                                                Rock
Gabriela                                                               Pop
Yellow                                                    Alternative Rock
Locked out of Heaven                                                   Pop
I Wanna Be Yours                                                Indie Rock
Who                                                       Contemporary R&B
VOY A LLeVARTE PA PR                                             Reggaeton
daño (w/ Tito Double P)                                  Regional Mexicano
Starboy (w/ Daft Punk)                                                 R&B
Lose Control                                                           Pop
Riptide                                                               Rock
WILDFLOWER                                                 Alternative Pop
LA CANCIÓN (w/ Bad Bunny)                                       Electronic
Qué Pasaría... (w/ Bad Bunny)                                    Reggaeton
Feel Good Inc                                                   Electronic
All The Stars (w/ SZA)                                             Hip Hop
See You Again (w/ Kali Uchis)                                      Hip Hop
In the End                                                        Nu Metal
One Of The Girls (w/ JENNIE, Lily-Rose Depp)                           R&B
Danza Kuduro (w/ Lucenzo)                                        Reggaeton
Aperture                                                               Pop
La Plena - W Sound 05 (w/ Beéle, Ovy On The Drums)               Reggaeton
LA VILLA (w/ Kapo, Gangsta)                                           Rock
Good Luck, Babe!                                                       Pop
Viva La Vida                                              Alternative Rock
As It Was                                                              Pop
We Are The People                                               Electronic
The Less I Know The Better                                Psychedelic Rock
505                                                             Indie Rock
Seven (w/ Latto)                                                       Pop
Marlboro Rojo                                             Regional Mexican
Todo Lo Fue                                              Regional Mexicano
The Visitor                                                       Pop Soul
Billie Jean                                                            Pop
Si Antes Te Hubiera Conocido                                     Reggaeton
Pvta Luna                                                Regional Mexicano
Ya Borracho                                              Regional Mexicano
undressed                                                        Indie Pop
Shape of You                                                           Pop
That’s So True                                                    Folk Pop
Midnight Sun                                                     Dance-Pop
When I Was Your Man                                                    Pop
Have You Ever Seen The Rain                                     Swamp Rock
Sparks                                                    Alternative Rock
COQUETA (w/ Grupo Frontera)                              Regional Mexicano
Somewhere Only We Know                                    Alternative Rock
Taste Back                                                            Rock
Zoo (w/ Shakira)                                    Special Purpose Artist
Smells Like Teen Spirit - Remastered                                Grunge
Blinding Lights                                                        R&B
7-3 (w/ Tito Double P)                                   Regional Mexicano
Porch Light                                                       Folk Pop
Just the Way You Are                                                   Pop
Coming Up Roses                                                        Pop
Nice To Each Other                                                     Pop
Counting Stars                                                         Pop
Fame is a Gun                                                          Pop
Only Girl (In The World)                                               Pop
Bring Me To Life                                                      Rock
Don't Stop The Music                                                   Pop
Timeless (w/ Playboi Carti)                                            R&B
Promiscuous (w/ Timbaland)                                             Pop
Give Me Everything (w/ Ne-Yo, AFROJACK, Nayer)                   Dance-Pop
chiclona (w/ Tito Double P, LENCHO)                      Regional Mexicano
no tiene sentido                                                     Latin
Kiss It Better                                                         Pop
Body                                                     Billboard Hot 100
The Night We Met                                                Indie Rock
Sweet Child O' Mine                                              Hard Rock
Let Me Love You (w/ Justin Bieber)                                   Dance
Numb                                                              Nu Metal
Africa                                                                Rock
Who Knows                                                          Toronto
The Man Who Can't Be Moved                                            Rock
A Couple Minutes                                                       Pop
Everybody Wants To Rule The World                                 New Wave
No One Noticed                                                        Rock
Without Me                                                         Hip Hop
Hips Don't Lie (w/ Wyclef Jean)                                        Pop
Me Rehúso                                                       Soundtrack
VeLDÁ (w/ Omar Courtz, Dei V)                                    Reggaeton
Style                                                                  Pop
Payphone (w/ Wiz Khalifa)                                              Pop
Please Please Please                                                   Pop
TU SANCHO                                                Billboard Hot 100
Shut up My Moms Calling                                                R&B
Ready, Steady, Go!                                                     Pop
We Found Love (w/ Calvin Harris)                                       Pop
Sex on Fire                                               Alternative Rock
Wonderwall - Remastered                                            Britpop
Too Sweet                                                              Pop
Can't Hold Us (w/ Macklemore, Ryan Lewis, Ray D...                 Hip Hop
DAISIES                                                                Pop
Sunflower - Spider-Man: Into the Spider-Verse (...                     Pop
Take on Me - 2015 Remaster                                             Pop
Can't Stop - 2014 Remaster                                Alternative Rock
Poker Face                                                             Pop
Cruel Summer                                                           Pop
Boys Don't Cry                                                    New Wave
luther                                                             Hip Hop
What You Saying                                                        Rap
S&M                                                                    Pop
No Pole                                                  Billboard Hot 100
Last Friday Night (T.G.I.F.)                                           Pop
Just Keep Watching (From F1® The Movie) (w/ F1 ...             Dolby Atmos
Flashing Lights (w/ Dwele)                                             Pop
Gangsta's Paradise (w/ L.V.)                                       Hip Hop
nuts (w/ rainy bear)                                               Hip Hop
Perfect                                                                Pop
Summertime Sadness                                               Indie Pop
Come As You Are - Remastered                                        Grunge
Breakin' Dishes                                                        Pop
The Chain - 2004 Remaster                                             Rock
Love On The Brain                                                     Soul
Sign of the Times                                                      Pop
Sorry                                                                  Pop
Life Goes On                                                         K-Pop
Alex Warren                                                            Pop