In [130]:
import matplotlib.pyplot as plt 
import pandas as pd
import numpy as np

In [131]:
spotify_database = pd.read_csv(
    "spotify_global_trends_2026 - spotify_global_trends_final.csv", 
    index_col=0)
spotify_dtb_df = pd.DataFrame(spotify_database)

In [132]:
spotify_dtb_df

,artist_name,streams,stream_change,7day,genre,country,pos,days,viral_score,trend,popularity_category,longevity
track_name,,,,,,,,,,,,
SWIM,BTS,11273830,-3370522,25918182,K-Pop,KR,1,2,37192012,Falling,Trending,New
Body to Body,BTS,6815694,-4369341,18000729,K-Pop,KR,2,2,24816423,Falling,Trending,New
Babydoll,Dominic Fike,5733862,178968,36599831,Alternative Pop,Florida,3,119,42333693,Rising,Trending,Evergreen
Hooligan,BTS,5338608,-3396855,14074071,K-Pop,KR,4,2,19412679,Falling,Trending,New
FYA,BTS,5196767,-2873904,13267438,K-Pop,KR,5,2,18464205,Falling,Trending,New
NORMAL,BTS,4749288,-2410388,11908964,K-Pop,KR,6,2,16658252,Falling,Average,New
Stateside + Zara Larsson (w/ Zara Larsson),PinkPantheress,4738329,-235112,34238168,Uk Garage,England,7,74,38976497,Falling,Average,Stable Hit
Aliens,BTS,4718569,-3036604,12473742,K-Pop,KR,8,2,17192311,Falling,Average,New
2,BTS,4573989,-2809104,11957082,K-Pop,KR,9,2,16531071,Falling,Average,New
Like Animals,BTS,4567309,-2259887,11394505,K-Pop,KR,10,2,15961814,Falling,Average,New
Merry Go Round,BTS,4490039,-2740868,11720946,K-Pop,KR,11,2,16210985,Falling,Average,New
they don’t know ’bout us,BTS,4423675,-2305775,11153125,K-Pop,KR,12,2,15576800,Falling,Average,New
Man I Need,Olivia Dean,4300853,-86237,28683798,Pop,US,13,214,32984651,Falling,Average,Evergreen
DtMF,Bad Bunny,4274742,-111657,29551375,Pop,PR,14,441,33826117,Falling,Average,Evergreen
End of Beginning,Djo,4108838,51706,27783861,Synth-Pop,US,15,764,31892699,Rising,Average,Evergreen
Risk It All,Bruno Mars,4007478,-499146,31739152,Offizielle Charts,US,16,23,35746630,Falling,Average,New
One More Night,BTS,3979999,-2153273,10113271,K-Pop,KR,17,2,14093270,Falling,Average,New
So Easy (To Fall In Love),Olivia Dean,3932082,33687,27406397,Pop,US,18,176,31338479,Rising,Average,Evergreen
Please,BTS,3897341,-2024958,9819640,K-Pop,KR,19,2,13716981,Falling,Average,New
Raindance (w/ Tems),Dave,3876044,-197505,25945780,Rap,US,20,109,29821824,Falling,Average,Evergreen
No. 29,BTS,3769141,-2733812,10272094,K-Pop,KR,21,2,14041235,Falling,Average,New
Into the Sun,BTS,3766459,-1959266,9492184,K-Pop,KR,22,2,13258643,Falling,Average,New
The Fate of Ophelia,Taylor Swift,3721332,-164240,26075129,Pop,US,23,170,29796461,Falling,Average,Evergreen
back to friends,sombr,3583316,-131585,25787563,Indie Pop,US,25,369,29370879,Falling,Average,Evergreen
BAILE INoLVIDABLE,Bad Bunny,3344867,-44475,22663387,Reggaeton,PR,26,441,26008254,Falling,Average,Evergreen
Lush Life,Zara Larsson,3341957,-21457,21857968,Pop,SE,27,761,25199925,Falling,Average,Evergreen
WHERE IS MY HUSBAND!,RAYE,3241010,5314,22068930,Pop,GB,28,184,25309940,Rising,Average,Evergreen
NUEVAYoL,Bad Bunny,3221298,-80099,21951925,Reggaeton,PR,29,441,25173223,Falling,Average,Evergreen
American Girls,Harry Styles,3101460,-420059,24771218,Rock,England,31,16,27872678,Falling,Average,New
iloveitiloveitiloveit,Bella Kay,2978129,-293545,22515039,Billboard Hot 100,US,32,30,25493168,Falling,Average,New
I Just Might,Bruno Mars,2860193,-16107,19846361,Pop,US,33,72,22706554,Falling,Average,Stable Hit
Iris,The Goo Goo Dolls,2776320,-126309,19907609,Alternative Rock,US,34,919,22683929,Falling,Average,Evergreen
Die With A Smile (w/ Bruno Mars),Lady Gaga,2691880,-142292,19325340,Pop,US,35,583,22017220,Falling,Average,Evergreen
Manchild,Sabrina Carpenter,2649376,-38989,17388953,Pop,US,36,289,20038329,Falling,Average,Evergreen
Tití Me Preguntó,Bad Bunny,2649180,-7253,17660827,Reggaeton,PR,37,483,20310007,Falling,Average,Evergreen
Love Me Not,Ravyn Lenae,2547681,-24120,17684406,Pop,US,38,368,20232087,Falling,Average,Evergreen
EoO,Bad Bunny,2542905,-123890,17968199,Billboard Hot 100,PR,39,437,20511104,Falling,Average,Evergreen
White Keys,Dominic Fike,2531236,-178737,17360808,Offizielle Charts,Florida,40,28,19892044,Falling,Average,New
BIRDS OF A FEATHER,Billie Eilish,2529075,24180,17056445,Alternative Pop,US,41,674,19585520,Rising,Average,Evergreen
Die On This Hill,SIENNA SPIRO,2398309,-322885,19212395,Pop,GB,43,102,21610704,Falling,Average,Evergreen
Every Breath You Take,The Police,2367833,25446,16070168,New Wave,GB,44,1619,18438001,Rising,Average,Evergreen
Dracula - JENNIE Remix (w/ JENNIE),Tame Impala,2332341,-89323,15767565,Psychedelic Rock,AU,45,36,18099906,Falling,Average,Stable Hit
12 to 12,sombr,2260402,-86182,15853606,Indie Pop,US,46,236,18114008,Falling,Average,Evergreen
Mr. Brightside,The Killers,2220784,-28156,14355698,Rock,GB,47,1682,16576482,Falling,Average,Evergreen
Espresso,Sabrina Carpenter,2213750,90339,13566149,Pop,US,48,709,15779899,Rising,Average,Evergreen
Choosin' Texas,Ella Langley,2169091,10331,13900513,Country,US,49,80,16069604,Rising,Average,Stable Hit
I Thought I Saw Your Face Today,She & Him,2155500,-138406,15647967,Indie Pop,US,50,104,17803467,Falling,Average,Evergreen
(When You Gonna) Give It Up to Me (w/ Keyshia Cole),Sean Paul,2154338,-112939,14951009,Dancehall,JM,51,65,17105347,Falling,Average,Stable Hit
Homewrecker,sombr,2139700,-220893,15402927,Indie Pop,US,52,44,17542627,Falling,Average,Stable Hit
Sailor Song,Gigi Perez,2107410,-121996,16461691,Electronic,IT,53,581,18569101,Falling,Average,Evergreen
Beautiful Things,Benson Boone,2090231,129461,13021976,Pop,US,54,793,15112207,Rising,Average,Evergreen
Sweater Weather,The Neighbourhood,2068795,-177998,15845100,Rock,GB,56,2120,17913895,Falling,Average,Evergreen
"One Dance (w/ Wizkid, Kyla)",Drake,2035423,-105895,13481976,Hip Hop,CA,57,2135,15517399,Falling,Average,Evergreen
Rein Me In (w/ Olivia Dean),Sam Fender,2020602,-34643,12610414,Rock,GB,58,23,14631016,Falling,Average,New
Creep,Radiohead,2011657,-91449,14176633,Rock,GB,59,842,16188290,Falling,Average,Evergreen
Opalite,Taylor Swift,1992549,-70008,14093798,Pop,US,60,170,16086347,Falling,Average,Evergreen
FEVER DREAM,Alex Warren,1992250,-130117,13935046,Offizielle Charts,GB,61,23,15927296,Falling,Average,New
dopamina (w/ Tito Double P),Peso Pluma,1952764,66159,12629601,Regional Mexicano,MX,62,86,14582365,Rising,Average,Stable Hit
E85,Don Toliver,1948495,-127853,13479304,Billboard Hot 100,US,63,51,15427799,Falling,Average,Stable Hit
That's What I Like,Bruno Mars,1912383,-142486,12699826,Pop,US,65,1254,14612209,Falling,Average,Evergreen
Dracula,Tame Impala,1906471,-84531,13354497,Dance-Pop,AU,66,138,15260968,Falling,Average,Evergreen
Dreams - 2004 Remaster,Fleetwood Mac,1894536,109844,11986886,Rock,GB,67,1004,13881422,Rising,Average,Evergreen
Gabriela,KATSEYE,1850006,60664,12468922,Girl Group,US,68,275,14318928,Rising,Average,Evergreen
Yellow,Coldplay,1828666,-99526,12862160,Alternative Rock,GB,69,1909,14690826,Falling,Average,Evergreen
Locked out of Heaven,Bruno Mars,1827015,-180903,13448378,Pop,US,70,1548,15275393,Falling,Average,Evergreen
I Wanna Be Yours,Arctic Monkeys,1825413,-80003,13563046,Indie Rock,GB,71,1354,15388459,Falling,Average,Evergreen
Who,Jimin,1807214,176731,11524586,Contemporary R&B,KR,72,611,13331800,Rising,Average,Evergreen
VOY A LLeVARTE PA PR,Bad Bunny,1780848,-133648,12359622,Reggaeton,PR,74,375,14140470,Falling,Average,Evergreen
daño (w/ Tito Double P),Peso Pluma,1780764,34375,11510694,Regional Mexicano,MX,75,86,13291458,Rising,Average,Stable Hit
Starboy (w/ Daft Punk),The Weeknd,1761445,-119116,12541479,R&B,CA,76,2095,14302924,Falling,Average,Evergreen
Lose Control,Teddy Swims,1737868,29374,11380332,Pop,US,77,856,13118200,Rising,Average,Evergreen
Riptide,Vance Joy,1737857,-5537,11544093,Rock,AU,78,2586,13281950,Falling,Average,Evergreen
WILDFLOWER,Billie Eilish,1730195,-201850,13900491,Alternative Pop,US,79,674,15630686,Falling,Average,Evergreen
LA CANCIÓN (w/ Bad Bunny),J Balvin,1708412,3072,11498926,Electronic,CO,80,988,13207338,Rising,Average,Evergreen
Qué Pasaría... (w/ Bad Bunny),Rauw Alejandro,1674168,25719,11406360,Reggaeton,PR,82,427,13080528,Rising,Average,Evergreen
Feel Good Inc,Gorillaz,1669648,-99808,11921501,Electronic,England,83,443,13591149,Falling,Average,Evergreen
All The Stars (w/ SZA),Kendrick Lamar,1665602,-10997,11456499,Hip Hop,US,84,1016,13122101,Falling,Average,Evergreen
See You Again (w/ Kali Uchis),"Tyler, The Creator",1662229,73090,10586720,Hip Hop,US,85,1066,12248949,Rising,Average,Evergreen
In the End,Linkin Park,1647656,-111701,11401354,Nu Metal,US,86,1012,13049010,Falling,Average,Evergreen
"One Of The Girls (w/ JENNIE, Lily-Rose Depp)",The Weeknd,1643774,-137154,12741548,R&B,CA,87,896,14385322,Falling,Average,Evergreen
Danza Kuduro (w/ Lucenzo),Don Omar,1643700,-105775,10737763,Reggaeton,PR,88,802,12381463,Falling,Average,Evergreen
Aperture,Harry Styles,1643576,-159524,13195579,Pop,England,89,58,14839155,Falling,Average,Stable Hit
"La Plena - W Sound 05 (w/ Beéle, Ovy On The Drums)",W Sound,1639753,-17075,10668572,Falcom,JP,90,389,12308325,Falling,Average,Evergreen
"LA VILLA (w/ Kapo, Gangsta)",Ryan Castro,1634806,64909,10801896,Rock,US,91,75,12436702,Rising,Average,Stable Hit
"Good Luck, Babe!",Chappell Roan,1621060,15852,10803226,Pop,US,92,710,12424286,Rising,Average,Evergreen
Viva La Vida,Coldplay,1610233,106290,10117917,Alternative Rock,GB,93,1329,11728150,Rising,Average,Evergreen
As It Was,Harry Styles,1608775,-150504,11660629,Pop,England,94,1401,13269404,Falling,Average,Evergreen
We Are The People,Empire Of The Sun,1594097,-30037,11149329,Electronic,AU,95,242,12743426,Falling,Average,Evergreen
The Less I Know The Better,Tame Impala,1593781,-51333,10870662,Psychedelic Rock,AU,96,510,12464443,Falling,Average,Evergreen
505,Arctic Monkeys,1587695,-113645,11653237,Indie Rock,GB,97,1537,13240932,Falling,Average,Evergreen
Seven (w/ Latto),Jung Kook,1580746,-80854,11202875,Pop,KR,98,981,12783621,Falling,Average,Evergreen
Marlboro Rojo,Fuerza Regida,1564019,112870,10014833,Billboard Hot 100,MX,99,317,11578852,Rising,Average,Evergreen
Todo Lo Fue,Lenin Ramírez,1563733,90601,10043908,Regional Mexicano,MX,100,58,11607641,Rising,Average,Stable Hit
The Visitor,SIENNA SPIRO,1558344,-296012,12044907,Pop Soul,GB,101,9,13603251,Falling,Average,New
Billie Jean,Michael Jackson,1551069,20972,9991848,Pop,US,102,363,11542917,Rising,Average,Evergreen
Si Antes Te Hubiera Conocido,KAROL G,1540953,46742,9623813,Reggaeton,CO,103,583,11164766,Rising,Average,Evergreen
Pvta Luna,Neton Vega,1537690,56324,10293259,Regional Mexicano,Culiacán,104,127,11830949,Rising,Average,Evergreen
Ya Borracho,Herencia De Grandes,1536251,49704,9999127,Regional Mexicano,Monterrey,105,122,11535378,Rising,Average,Evergreen
undressed,sombr,1535615,-88400,10972970,Indie Pop,US,106,358,12508585,Falling,Average,Evergreen
Shape of You,Ed Sheeran,1532739,-41473,10263688,Pop,GB,107,2815,11796427,Falling,Average,Evergreen
That’s So True,Gracie Abrams,1526228,-51917,10719195,Folk Pop,US,108,519,12245423,Falling,Average,Evergreen
Midnight Sun,Zara Larsson,1512185,-10911,10133254,Dance-Pop,SE,109,63,11645439,Falling,Average,Stable Hit
When I Was Your Man,Bruno Mars,1508958,144568,10366342,Pop,US,110,1476,11875300,Rising,Average,Evergreen
Have You Ever Seen The Rain,Creedence Clearwater Revival,1507387,52997,9344647,Swamp Rock,US,111,484,10852034,Rising,Average,Evergreen
Sparks,Coldplay,1504857,-3015,10932582,Alternative Rock,GB,112,562,12437439,Falling,Average,Evergreen
COQUETA (w/ Grupo Frontera),Fuerza Regida,1503126,62199,9876432,Regional Mexicano,MX,113,309,11379558,Rising,Average,Evergreen
Somewhere Only We Know,Keane,1496326,10006,10165562,Alternative Rock,GB,114,1193,11661888,Rising,Average,Evergreen
Taste Back,Harry Styles,1480809,-206276,12746602,Rock,England,115,16,14227411,Falling,Average,New
Zoo (w/ Shakira),Disney,1466813,189999,4001191,Special Purpose Artist,US,116,58,5468004,Rising,Average,Stable Hit
Smells Like Teen Spirit - Remastered,Nirvana,1453513,-125183,10271555,Grunge,US,117,727,11725068,Falling,Average,Evergreen
Blinding Lights,The Weeknd,1448450,11224,9729402,R&B,CA,118,2301,11177852,Rising,Average,Evergreen
7-3 (w/ Tito Double P),Peso Pluma,1440677,5573,9736835,Regional Mexicano,MX,119,86,11177512,Rising,Average,Stable Hit
Porch Light,Noah Kahan,1430611,-374516,12359863,Folk Pop,US,120,9,13790474,Falling,Average,New
Just the Way You Are,Bruno Mars,1423798,-102703,10482326,Pop,US,121,1197,11906124,Falling,Average,Evergreen
Coming Up Roses,Harry Styles,1418986,-230104,12650537,Pop,England,122,16,14069523,Falling,Average,New
Nice To Each Other,Olivia Dean,1416007,-50721,9872551,Pop,US,123,212,11288558,Falling,Average,Evergreen
Counting Stars,OneRepublic,1414383,-31879,9525522,Pop,US,124,2495,10939905,Falling,Average,Evergreen
Fame is a Gun,Addison Rae,1404894,-2613,10047427,Pop,US,125,120,11452321,Falling,Average,Evergreen
Only Girl (In The World),Rihanna,1398296,-52230,9276305,Pop,US,126,131,10674601,Falling,Average,Evergreen
Bring Me To Life,Evanescence,1396427,-131213,10205781,Rock,US,127,341,11602208,Falling,Average,Evergreen
Don't Stop The Music,Rihanna,1395227,-40325,9282714,Pop,US,128,117,10677941,Falling,Average,Evergreen
Timeless (w/ Playboi Carti),The Weeknd,1392146,-94943,10349253,R&B,CA,129,541,11741399,Falling,Average,Evergreen
Promiscuous (w/ Timbaland),Nelly Furtado,1390532,-5054,8860680,Pop,CA,130,171,10251212,Falling,Average,Evergreen
"Give Me Everything (w/ Ne-Yo, AFROJACK, Nayer)",Pitbull,1389531,-110927,9497950,Dance-Pop,US,131,511,10887481,Falling,Average,Evergreen
"chiclona (w/ Tito Double P, LENCHO)",Peso Pluma,1389411,-12742,9202643,Regional Mexicano,MX,132,21,10592054,Falling,Average,New
no tiene sentido,Beéle,1380148,-55381,9480736,Latin,CO,133,287,10860884,Falling,Average,Evergreen
Kiss It Better,Rihanna,1379747,-223043,10359276,Pop,US,134,142,11739023,Falling,Average,Evergreen
Body,Don Toliver,1377373,-100397,10001871,Billboard Hot 100,US,135,51,11379244,Falling,Average,Stable Hit
The Night We Met,Lord Huron,1368186,-94429,10515041,Indie Rock,US,137,1327,11883227,Falling,Average,Evergreen
Sweet Child O' Mine,Guns N' Roses,1367839,-13859,8983873,Hard Rock,US,138,440,10351712,Falling,Average,Evergreen
Let Me Love You (w/ Justin Bieber),DJ Snake,1364636,-88823,10084292,Dance,FR,139,809,11448928,Falling,Average,Evergreen
Numb,Linkin Park,1350782,-120313,9629438,Nu Metal,US,140,704,10980220,Falling,Average,Evergreen
Africa,TOTO,1350745,-23426,7537107,Rock,US,141,753,8887852,Falling,Average,Evergreen
Who Knows,Daniel Caesar,1349819,-151500,10486538,Toronto,CA,142,120,11836357,Falling,Average,Evergreen
The Man Who Can't Be Moved,The Script,1349075,-126873,10424946,Rock,GB,143,157,11774021,Falling,Average,Evergreen
A Couple Minutes,Olivia Dean,1348112,-57009,9770863,Pop,US,144,118,11118975,Falling,Average,Evergreen
Everybody Wants To Rule The World,Tears For Fears,1345799,28946,6232525,New Wave,GB,145,1027,7578324,Rising,Average,Evergreen
No One Noticed,The Marías,1342468,-53818,10132311,Rock,GB,146,496,11474779,Falling,Average,Evergreen
Without Me,Eminem,1335886,-100932,9154300,Hip Hop,US,147,1637,10490186,Falling,Average,Evergreen
Hips Don't Lie (w/ Wyclef Jean),Shakira,1330852,24927,6218904,Pop,CO,148,338,7549756,Rising,Average,Evergreen
Me Rehúso,Danny Ocean,1326162,-38797,8914757,Soundtrack,US,149,617,10240919,Falling,Average,Evergreen
"VeLDÁ (w/ Omar Courtz, Dei V)",Bad Bunny,1326149,-90827,9468025,Reggaeton,PR,150,395,10794174,Falling,Average,Evergreen
Style,Taylor Swift,1311077,-73973,8934698,Pop,US,152,347,10245775,Falling,Average,Evergreen
Payphone (w/ Wiz Khalifa),Maroon 5,1306200,-28788,9226178,Pop,US,153,712,10532378,Falling,Average,Evergreen
Please Please Please,Sabrina Carpenter,1296957,-1727,5009467,Pop,US,154,503,6306424,Falling,Average,Evergreen
TU SANCHO,Fuerza Regida,1296297,19803,8708123,Billboard Hot 100,MX,155,284,10004420,Rising,Average,Evergreen
Shut up My Moms Calling,Hotel Ugly,1294677,-8737,9158699,R&B,US,156,773,10453376,Falling,Average,Evergreen
"Ready, Steady, Go!",Harry Styles,1294001,-190275,11338844,Pop,England,157,16,12632845,Falling,Average,New
We Found Love (w/ Calvin Harris),Rihanna,1292535,-110188,7904030,Pop,US,158,823,9196565,Falling,Average,Evergreen
Sex on Fire,Kings of Leon,1290404,5746,3835428,Alternative Rock,US,159,63,5125832,Rising,Average,Stable Hit
Wonderwall - Remastered,Oasis,1286520,-64148,8821556,Britpop,GB,160,884,10108076,Falling,Average,Evergreen
Too Sweet,Hozier,1283948,40456,6149401,Pop,IE,161,620,7433349,Rising,Average,Evergreen
"Can't Hold Us (w/ Macklemore, Ryan Lewis, Ray Dalton)",Macklemore & Ryan Lewis,1282248,-87604,8781747,Hip Hop,US,163,1211,10063995,Falling,Average,Evergreen
DAISIES,Justin Bieber,1281664,-20169,8990092,Pop,CA,164,252,10271756,Falling,Average,Evergreen
Sunflower - Spider-Man: Into the Spider-Verse (w/ Swae Lee),Post Malone,1281251,-6790,5025791,Pop,US,165,2292,6307042,Falling,Average,Evergreen
Take on Me - 2015 Remaster,a-ha,1279646,-21334,4937908,Pop,NO,167,14,6217554,Falling,Average,New
Can't Stop - 2014 Remaster,Red Hot Chili Peppers,1275766,-114450,9103531,Alternative Rock,US,169,20,10379297,Falling,Average,New
Poker Face,Lady Gaga,1275472,-64590,8736190,Pop,US,170,389,10011662,Falling,Average,Evergreen
Cruel Summer,Taylor Swift,1268541,9198,2527884,Pop,US,172,1014,3796425,Rising,Average,Evergreen
Boys Don't Cry,The Cure,1263767,15843,6006104,New Wave,GB,173,53,7269871,Rising,Average,Stable Hit
luther,Kendrick Lamar,1260494,-89450,9151667,Hip Hop,US,175,483,10412161,Falling,Average,Evergreen
What You Saying,Lil Uzi Vert,1259173,-27420,8754899,Rap,US,176,80,10014072,Falling,Average,Stable Hit
S&M,Rihanna,1257351,-87753,7352626,Pop,US,177,30,8609977,Falling,Average,New
No Pole,Don Toliver,1254541,-53350,9273774,Billboard Hot 100,US,178,454,10528315,Falling,Average,Evergreen
Last Friday Night (T.G.I.F.),Katy Perry,1251765,-19664,2523194,Pop,US,179,99,3774959,Falling,Average,Stable Hit
Just Keep Watching (From F1® The Movie) (w/ F1 The Album),Tate McRae,1245007,-77995,9035434,Dolby Atmos,CA,181,270,10280441,Falling,Average,Evergreen
Flashing Lights (w/ Dwele),Kanye West,1241168,-39451,8480893,Pop,GB,185,244,9722061,Falling,Average,Evergreen
Gangsta's Paradise (w/ L.V.),Coolio,1239884,-37552,4891917,Hip Hop,US,187,791,6131801,Falling,Average,Evergreen
nuts (w/ rainy bear),Lil Peep,1237223,-11727,4787172,Hip Hop,US,188,5,6024395,Falling,Average,New
Perfect,Ed Sheeran,1227709,-74196,8956978,Pop,GB,190,3070,10184687,Falling,Average,Evergreen
Summertime Sadness,Lana Del Rey,1227362,-104470,7508206,Indie Pop,US,191,1093,8735568,Falling,Average,Evergreen
Come As You Are - Remastered,Nirvana,1224750,-89453,6372663,Grunge,US,192,153,7597413,Falling,Average,Evergreen
Breakin' Dishes,Rihanna,1224675,-24245,8638532,Pop,US,193,346,9863207,Falling,Average,Evergreen
The Chain - 2004 Remaster,Fleetwood Mac,1210598,-79537,8817306,Rock,GB,196,205,10027904,Falling,Average,Evergreen
Love On The Brain,Rihanna,1203160,-69820,7439269,Soul,US,197,352,8642429,Falling,Average,Evergreen
Sign of the Times,Harry Styles,1198929,-121566,3816744,Pop,England,198,331,5015673,Falling,Average,Evergreen
Sorry,Justin Bieber,1192146,-86760,7346804,Pop,CA,199,767,8538950,Falling,Average,Evergreen
Life Goes On,BTS,1191777,-76127,8979038,K-Pop,KR,200,207,10170815,Falling,Average,Evergreen

In [133]:
spotify_dtb_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 178 entries, SWIM to Life Goes On
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   artist_name          178 non-null    object
 1   streams              178 non-null    int64
 2   stream_change        178 non-null    int64
 3   7day                 178 non-null    int64
 4   genre                178 non-null    object
 5   country              178 non-null    object
 6   pos                  178 non-null    int64
 7   days                 178 non-null    int64
 8   viral_score          178 non-null    int64
 9   trend                178 non-null    object
 10  popularity_category  178 non-null    object
 11  longevity            178 non-null    object
dtypes: int64(6), object(6)
memory usage: 18.1+ KB

In [134]:
spotify_dtb_df = spotify_dtb_df.rename(columns={
    "artist_name" : "artist",
    "pos" : "position",
    "days" : "days_on_chart",
    '7day': 'streams_7day'
})

spotify_dtb_df

,artist,streams,stream_change,streams_7day,genre,country,position,days_on_chart,viral_score,trend,popularity_category,longevity
track_name,,,,,,,,,,,,
SWIM,BTS,11273830,-3370522,25918182,K-Pop,KR,1,2,37192012,Falling,Trending,New
Body to Body,BTS,6815694,-4369341,18000729,K-Pop,KR,2,2,24816423,Falling,Trending,New
Babydoll,Dominic Fike,5733862,178968,36599831,Alternative Pop,Florida,3,119,42333693,Rising,Trending,Evergreen
Hooligan,BTS,5338608,-3396855,14074071,K-Pop,KR,4,2,19412679,Falling,Trending,New
FYA,BTS,5196767,-2873904,13267438,K-Pop,KR,5,2,18464205,Falling,Trending,New
NORMAL,BTS,4749288,-2410388,11908964,K-Pop,KR,6,2,16658252,Falling,Average,New
Stateside + Zara Larsson (w/ Zara Larsson),PinkPantheress,4738329,-235112,34238168,Uk Garage,England,7,74,38976497,Falling,Average,Stable Hit
Aliens,BTS,4718569,-3036604,12473742,K-Pop,KR,8,2,17192311,Falling,Average,New
2,BTS,4573989,-2809104,11957082,K-Pop,KR,9,2,16531071,Falling,Average,New
Like Animals,BTS,4567309,-2259887,11394505,K-Pop,KR,10,2,15961814,Falling,Average,New
Merry Go Round,BTS,4490039,-2740868,11720946,K-Pop,KR,11,2,16210985,Falling,Average,New
they don’t know ’bout us,BTS,4423675,-2305775,11153125,K-Pop,KR,12,2,15576800,Falling,Average,New
Man I Need,Olivia Dean,4300853,-86237,28683798,Pop,US,13,214,32984651,Falling,Average,Evergreen
DtMF,Bad Bunny,4274742,-111657,29551375,Pop,PR,14,441,33826117,Falling,Average,Evergreen
End of Beginning,Djo,4108838,51706,27783861,Synth-Pop,US,15,764,31892699,Rising,Average,Evergreen
Risk It All,Bruno Mars,4007478,-499146,31739152,Offizielle Charts,US,16,23,35746630,Falling,Average,New
One More Night,BTS,3979999,-2153273,10113271,K-Pop,KR,17,2,14093270,Falling,Average,New
So Easy (To Fall In Love),Olivia Dean,3932082,33687,27406397,Pop,US,18,176,31338479,Rising,Average,Evergreen
Please,BTS,3897341,-2024958,9819640,K-Pop,KR,19,2,13716981,Falling,Average,New
Raindance (w/ Tems),Dave,3876044,-197505,25945780,Rap,US,20,109,29821824,Falling,Average,Evergreen
No. 29,BTS,3769141,-2733812,10272094,K-Pop,KR,21,2,14041235,Falling,Average,New
Into the Sun,BTS,3766459,-1959266,9492184,K-Pop,KR,22,2,13258643,Falling,Average,New
The Fate of Ophelia,Taylor Swift,3721332,-164240,26075129,Pop,US,23,170,29796461,Falling,Average,Evergreen
back to friends,sombr,3583316,-131585,25787563,Indie Pop,US,25,369,29370879,Falling,Average,Evergreen
BAILE INoLVIDABLE,Bad Bunny,3344867,-44475,22663387,Reggaeton,PR,26,441,26008254,Falling,Average,Evergreen
Lush Life,Zara Larsson,3341957,-21457,21857968,Pop,SE,27,761,25199925,Falling,Average,Evergreen
WHERE IS MY HUSBAND!,RAYE,3241010,5314,22068930,Pop,GB,28,184,25309940,Rising,Average,Evergreen
NUEVAYoL,Bad Bunny,3221298,-80099,21951925,Reggaeton,PR,29,441,25173223,Falling,Average,Evergreen
American Girls,Harry Styles,3101460,-420059,24771218,Rock,England,31,16,27872678,Falling,Average,New
iloveitiloveitiloveit,Bella Kay,2978129,-293545,22515039,Billboard Hot 100,US,32,30,25493168,Falling,Average,New
I Just Might,Bruno Mars,2860193,-16107,19846361,Pop,US,33,72,22706554,Falling,Average,Stable Hit
Iris,The Goo Goo Dolls,2776320,-126309,19907609,Alternative Rock,US,34,919,22683929,Falling,Average,Evergreen
Die With A Smile (w/ Bruno Mars),Lady Gaga,2691880,-142292,19325340,Pop,US,35,583,22017220,Falling,Average,Evergreen
Manchild,Sabrina Carpenter,2649376,-38989,17388953,Pop,US,36,289,20038329,Falling,Average,Evergreen
Tití Me Preguntó,Bad Bunny,2649180,-7253,17660827,Reggaeton,PR,37,483,20310007,Falling,Average,Evergreen
Love Me Not,Ravyn Lenae,2547681,-24120,17684406,Pop,US,38,368,20232087,Falling,Average,Evergreen
EoO,Bad Bunny,2542905,-123890,17968199,Billboard Hot 100,PR,39,437,20511104,Falling,Average,Evergreen
White Keys,Dominic Fike,2531236,-178737,17360808,Offizielle Charts,Florida,40,28,19892044,Falling,Average,New
BIRDS OF A FEATHER,Billie Eilish,2529075,24180,17056445,Alternative Pop,US,41,674,19585520,Rising,Average,Evergreen
Die On This Hill,SIENNA SPIRO,2398309,-322885,19212395,Pop,GB,43,102,21610704,Falling,Average,Evergreen
Every Breath You Take,The Police,2367833,25446,16070168,New Wave,GB,44,1619,18438001,Rising,Average,Evergreen
Dracula - JENNIE Remix (w/ JENNIE),Tame Impala,2332341,-89323,15767565,Psychedelic Rock,AU,45,36,18099906,Falling,Average,Stable Hit
12 to 12,sombr,2260402,-86182,15853606,Indie Pop,US,46,236,18114008,Falling,Average,Evergreen
Mr. Brightside,The Killers,2220784,-28156,14355698,Rock,GB,47,1682,16576482,Falling,Average,Evergreen
Espresso,Sabrina Carpenter,2213750,90339,13566149,Pop,US,48,709,15779899,Rising,Average,Evergreen
Choosin' Texas,Ella Langley,2169091,10331,13900513,Country,US,49,80,16069604,Rising,Average,Stable Hit
I Thought I Saw Your Face Today,She & Him,2155500,-138406,15647967,Indie Pop,US,50,104,17803467,Falling,Average,Evergreen
(When You Gonna) Give It Up to Me (w/ Keyshia Cole),Sean Paul,2154338,-112939,14951009,Dancehall,JM,51,65,17105347,Falling,Average,Stable Hit
Homewrecker,sombr,2139700,-220893,15402927,Indie Pop,US,52,44,17542627,Falling,Average,Stable Hit
Sailor Song,Gigi Perez,2107410,-121996,16461691,Electronic,IT,53,581,18569101,Falling,Average,Evergreen
Beautiful Things,Benson Boone,2090231,129461,13021976,Pop,US,54,793,15112207,Rising,Average,Evergreen
Sweater Weather,The Neighbourhood,2068795,-177998,15845100,Rock,GB,56,2120,17913895,Falling,Average,Evergreen
"One Dance (w/ Wizkid, Kyla)",Drake,2035423,-105895,13481976,Hip Hop,CA,57,2135,15517399,Falling,Average,Evergreen
Rein Me In (w/ Olivia Dean),Sam Fender,2020602,-34643,12610414,Rock,GB,58,23,14631016,Falling,Average,New
Creep,Radiohead,2011657,-91449,14176633,Rock,GB,59,842,16188290,Falling,Average,Evergreen
Opalite,Taylor Swift,1992549,-70008,14093798,Pop,US,60,170,16086347,Falling,Average,Evergreen
FEVER DREAM,Alex Warren,1992250,-130117,13935046,Offizielle Charts,GB,61,23,15927296,Falling,Average,New
dopamina (w/ Tito Double P),Peso Pluma,1952764,66159,12629601,Regional Mexicano,MX,62,86,14582365,Rising,Average,Stable Hit
E85,Don Toliver,1948495,-127853,13479304,Billboard Hot 100,US,63,51,15427799,Falling,Average,Stable Hit
That's What I Like,Bruno Mars,1912383,-142486,12699826,Pop,US,65,1254,14612209,Falling,Average,Evergreen
Dracula,Tame Impala,1906471,-84531,13354497,Dance-Pop,AU,66,138,15260968,Falling,Average,Evergreen
Dreams - 2004 Remaster,Fleetwood Mac,1894536,109844,11986886,Rock,GB,67,1004,13881422,Rising,Average,Evergreen
Gabriela,KATSEYE,1850006,60664,12468922,Girl Group,US,68,275,14318928,Rising,Average,Evergreen
Yellow,Coldplay,1828666,-99526,12862160,Alternative Rock,GB,69,1909,14690826,Falling,Average,Evergreen
Locked out of Heaven,Bruno Mars,1827015,-180903,13448378,Pop,US,70,1548,15275393,Falling,Average,Evergreen
I Wanna Be Yours,Arctic Monkeys,1825413,-80003,13563046,Indie Rock,GB,71,1354,15388459,Falling,Average,Evergreen
Who,Jimin,1807214,176731,11524586,Contemporary R&B,KR,72,611,13331800,Rising,Average,Evergreen
VOY A LLeVARTE PA PR,Bad Bunny,1780848,-133648,12359622,Reggaeton,PR,74,375,14140470,Falling,Average,Evergreen
daño (w/ Tito Double P),Peso Pluma,1780764,34375,11510694,Regional Mexicano,MX,75,86,13291458,Rising,Average,Stable Hit
Starboy (w/ Daft Punk),The Weeknd,1761445,-119116,12541479,R&B,CA,76,2095,14302924,Falling,Average,Evergreen
Lose Control,Teddy Swims,1737868,29374,11380332,Pop,US,77,856,13118200,Rising,Average,Evergreen
Riptide,Vance Joy,1737857,-5537,11544093,Rock,AU,78,2586,13281950,Falling,Average,Evergreen
WILDFLOWER,Billie Eilish,1730195,-201850,13900491,Alternative Pop,US,79,674,15630686,Falling,Average,Evergreen
LA CANCIÓN (w/ Bad Bunny),J Balvin,1708412,3072,11498926,Electronic,CO,80,988,13207338,Rising,Average,Evergreen
Qué Pasaría... (w/ Bad Bunny),Rauw Alejandro,1674168,25719,11406360,Reggaeton,PR,82,427,13080528,Rising,Average,Evergreen
Feel Good Inc,Gorillaz,1669648,-99808,11921501,Electronic,England,83,443,13591149,Falling,Average,Evergreen
All The Stars (w/ SZA),Kendrick Lamar,1665602,-10997,11456499,Hip Hop,US,84,1016,13122101,Falling,Average,Evergreen
See You Again (w/ Kali Uchis),"Tyler, The Creator",1662229,73090,10586720,Hip Hop,US,85,1066,12248949,Rising,Average,Evergreen
In the End,Linkin Park,1647656,-111701,11401354,Nu Metal,US,86,1012,13049010,Falling,Average,Evergreen
"One Of The Girls (w/ JENNIE, Lily-Rose Depp)",The Weeknd,1643774,-137154,12741548,R&B,CA,87,896,14385322,Falling,Average,Evergreen
Danza Kuduro (w/ Lucenzo),Don Omar,1643700,-105775,10737763,Reggaeton,PR,88,802,12381463,Falling,Average,Evergreen
Aperture,Harry Styles,1643576,-159524,13195579,Pop,England,89,58,14839155,Falling,Average,Stable Hit
"La Plena - W Sound 05 (w/ Beéle, Ovy On The Drums)",W Sound,1639753,-17075,10668572,Falcom,JP,90,389,12308325,Falling,Average,Evergreen
"LA VILLA (w/ Kapo, Gangsta)",Ryan Castro,1634806,64909,10801896,Rock,US,91,75,12436702,Rising,Average,Stable Hit
"Good Luck, Babe!",Chappell Roan,1621060,15852,10803226,Pop,US,92,710,12424286,Rising,Average,Evergreen
Viva La Vida,Coldplay,1610233,106290,10117917,Alternative Rock,GB,93,1329,11728150,Rising,Average,Evergreen
As It Was,Harry Styles,1608775,-150504,11660629,Pop,England,94,1401,13269404,Falling,Average,Evergreen
We Are The People,Empire Of The Sun,1594097,-30037,11149329,Electronic,AU,95,242,12743426,Falling,Average,Evergreen
The Less I Know The Better,Tame Impala,1593781,-51333,10870662,Psychedelic Rock,AU,96,510,12464443,Falling,Average,Evergreen
505,Arctic Monkeys,1587695,-113645,11653237,Indie Rock,GB,97,1537,13240932,Falling,Average,Evergreen
Seven (w/ Latto),Jung Kook,1580746,-80854,11202875,Pop,KR,98,981,12783621,Falling,Average,Evergreen
Marlboro Rojo,Fuerza Regida,1564019,112870,10014833,Billboard Hot 100,MX,99,317,11578852,Rising,Average,Evergreen
Todo Lo Fue,Lenin Ramírez,1563733,90601,10043908,Regional Mexicano,MX,100,58,11607641,Rising,Average,Stable Hit
The Visitor,SIENNA SPIRO,1558344,-296012,12044907,Pop Soul,GB,101,9,13603251,Falling,Average,New
Billie Jean,Michael Jackson,1551069,20972,9991848,Pop,US,102,363,11542917,Rising,Average,Evergreen
Si Antes Te Hubiera Conocido,KAROL G,1540953,46742,9623813,Reggaeton,CO,103,583,11164766,Rising,Average,Evergreen
Pvta Luna,Neton Vega,1537690,56324,10293259,Regional Mexicano,Culiacán,104,127,11830949,Rising,Average,Evergreen
Ya Borracho,Herencia De Grandes,1536251,49704,9999127,Regional Mexicano,Monterrey,105,122,11535378,Rising,Average,Evergreen
undressed,sombr,1535615,-88400,10972970,Indie Pop,US,106,358,12508585,Falling,Average,Evergreen
Shape of You,Ed Sheeran,1532739,-41473,10263688,Pop,GB,107,2815,11796427,Falling,Average,Evergreen
That’s So True,Gracie Abrams,1526228,-51917,10719195,Folk Pop,US,108,519,12245423,Falling,Average,Evergreen
Midnight Sun,Zara Larsson,1512185,-10911,10133254,Dance-Pop,SE,109,63,11645439,Falling,Average,Stable Hit
When I Was Your Man,Bruno Mars,1508958,144568,10366342,Pop,US,110,1476,11875300,Rising,Average,Evergreen
Have You Ever Seen The Rain,Creedence Clearwater Revival,1507387,52997,9344647,Swamp Rock,US,111,484,10852034,Rising,Average,Evergreen
Sparks,Coldplay,1504857,-3015,10932582,Alternative Rock,GB,112,562,12437439,Falling,Average,Evergreen
COQUETA (w/ Grupo Frontera),Fuerza Regida,1503126,62199,9876432,Regional Mexicano,MX,113,309,11379558,Rising,Average,Evergreen
Somewhere Only We Know,Keane,1496326,10006,10165562,Alternative Rock,GB,114,1193,11661888,Rising,Average,Evergreen
Taste Back,Harry Styles,1480809,-206276,12746602,Rock,England,115,16,14227411,Falling,Average,New
Zoo (w/ Shakira),Disney,1466813,189999,4001191,Special Purpose Artist,US,116,58,5468004,Rising,Average,Stable Hit
Smells Like Teen Spirit - Remastered,Nirvana,1453513,-125183,10271555,Grunge,US,117,727,11725068,Falling,Average,Evergreen
Blinding Lights,The Weeknd,1448450,11224,9729402,R&B,CA,118,2301,11177852,Rising,Average,Evergreen
7-3 (w/ Tito Double P),Peso Pluma,1440677,5573,9736835,Regional Mexicano,MX,119,86,11177512,Rising,Average,Stable Hit
Porch Light,Noah Kahan,1430611,-374516,12359863,Folk Pop,US,120,9,13790474,Falling,Average,New
Just the Way You Are,Bruno Mars,1423798,-102703,10482326,Pop,US,121,1197,11906124,Falling,Average,Evergreen
Coming Up Roses,Harry Styles,1418986,-230104,12650537,Pop,England,122,16,14069523,Falling,Average,New
Nice To Each Other,Olivia Dean,1416007,-50721,9872551,Pop,US,123,212,11288558,Falling,Average,Evergreen
Counting Stars,OneRepublic,1414383,-31879,9525522,Pop,US,124,2495,10939905,Falling,Average,Evergreen
Fame is a Gun,Addison Rae,1404894,-2613,10047427,Pop,US,125,120,11452321,Falling,Average,Evergreen
Only Girl (In The World),Rihanna,1398296,-52230,9276305,Pop,US,126,131,10674601,Falling,Average,Evergreen
Bring Me To Life,Evanescence,1396427,-131213,10205781,Rock,US,127,341,11602208,Falling,Average,Evergreen
Don't Stop The Music,Rihanna,1395227,-40325,9282714,Pop,US,128,117,10677941,Falling,Average,Evergreen
Timeless (w/ Playboi Carti),The Weeknd,1392146,-94943,10349253,R&B,CA,129,541,11741399,Falling,Average,Evergreen
Promiscuous (w/ Timbaland),Nelly Furtado,1390532,-5054,8860680,Pop,CA,130,171,10251212,Falling,Average,Evergreen
"Give Me Everything (w/ Ne-Yo, AFROJACK, Nayer)",Pitbull,1389531,-110927,9497950,Dance-Pop,US,131,511,10887481,Falling,Average,Evergreen
"chiclona (w/ Tito Double P, LENCHO)",Peso Pluma,1389411,-12742,9202643,Regional Mexicano,MX,132,21,10592054,Falling,Average,New
no tiene sentido,Beéle,1380148,-55381,9480736,Latin,CO,133,287,10860884,Falling,Average,Evergreen
Kiss It Better,Rihanna,1379747,-223043,10359276,Pop,US,134,142,11739023,Falling,Average,Evergreen
Body,Don Toliver,1377373,-100397,10001871,Billboard Hot 100,US,135,51,11379244,Falling,Average,Stable Hit
The Night We Met,Lord Huron,1368186,-94429,10515041,Indie Rock,US,137,1327,11883227,Falling,Average,Evergreen
Sweet Child O' Mine,Guns N' Roses,1367839,-13859,8983873,Hard Rock,US,138,440,10351712,Falling,Average,Evergreen
Let Me Love You (w/ Justin Bieber),DJ Snake,1364636,-88823,10084292,Dance,FR,139,809,11448928,Falling,Average,Evergreen
Numb,Linkin Park,1350782,-120313,9629438,Nu Metal,US,140,704,10980220,Falling,Average,Evergreen
Africa,TOTO,1350745,-23426,7537107,Rock,US,141,753,8887852,Falling,Average,Evergreen
Who Knows,Daniel Caesar,1349819,-151500,10486538,Toronto,CA,142,120,11836357,Falling,Average,Evergreen
The Man Who Can't Be Moved,The Script,1349075,-126873,10424946,Rock,GB,143,157,11774021,Falling,Average,Evergreen
A Couple Minutes,Olivia Dean,1348112,-57009,9770863,Pop,US,144,118,11118975,Falling,Average,Evergreen
Everybody Wants To Rule The World,Tears For Fears,1345799,28946,6232525,New Wave,GB,145,1027,7578324,Rising,Average,Evergreen
No One Noticed,The Marías,1342468,-53818,10132311,Rock,GB,146,496,11474779,Falling,Average,Evergreen
Without Me,Eminem,1335886,-100932,9154300,Hip Hop,US,147,1637,10490186,Falling,Average,Evergreen
Hips Don't Lie (w/ Wyclef Jean),Shakira,1330852,24927,6218904,Pop,CO,148,338,7549756,Rising,Average,Evergreen
Me Rehúso,Danny Ocean,1326162,-38797,8914757,Soundtrack,US,149,617,10240919,Falling,Average,Evergreen
"VeLDÁ (w/ Omar Courtz, Dei V)",Bad Bunny,1326149,-90827,9468025,Reggaeton,PR,150,395,10794174,Falling,Average,Evergreen
Style,Taylor Swift,1311077,-73973,8934698,Pop,US,152,347,10245775,Falling,Average,Evergreen
Payphone (w/ Wiz Khalifa),Maroon 5,1306200,-28788,9226178,Pop,US,153,712,10532378,Falling,Average,Evergreen
Please Please Please,Sabrina Carpenter,1296957,-1727,5009467,Pop,US,154,503,6306424,Falling,Average,Evergreen
TU SANCHO,Fuerza Regida,1296297,19803,8708123,Billboard Hot 100,MX,155,284,10004420,Rising,Average,Evergreen
Shut up My Moms Calling,Hotel Ugly,1294677,-8737,9158699,R&B,US,156,773,10453376,Falling,Average,Evergreen
"Ready, Steady, Go!",Harry Styles,1294001,-190275,11338844,Pop,England,157,16,12632845,Falling,Average,New
We Found Love (w/ Calvin Harris),Rihanna,1292535,-110188,7904030,Pop,US,158,823,9196565,Falling,Average,Evergreen
Sex on Fire,Kings of Leon,1290404,5746,3835428,Alternative Rock,US,159,63,5125832,Rising,Average,Stable Hit
Wonderwall - Remastered,Oasis,1286520,-64148,8821556,Britpop,GB,160,884,10108076,Falling,Average,Evergreen
Too Sweet,Hozier,1283948,40456,6149401,Pop,IE,161,620,7433349,Rising,Average,Evergreen
"Can't Hold Us (w/ Macklemore, Ryan Lewis, Ray Dalton)",Macklemore & Ryan Lewis,1282248,-87604,8781747,Hip Hop,US,163,1211,10063995,Falling,Average,Evergreen
DAISIES,Justin Bieber,1281664,-20169,8990092,Pop,CA,164,252,10271756,Falling,Average,Evergreen
Sunflower - Spider-Man: Into the Spider-Verse (w/ Swae Lee),Post Malone,1281251,-6790,5025791,Pop,US,165,2292,6307042,Falling,Average,Evergreen
Take on Me - 2015 Remaster,a-ha,1279646,-21334,4937908,Pop,NO,167,14,6217554,Falling,Average,New
Can't Stop - 2014 Remaster,Red Hot Chili Peppers,1275766,-114450,9103531,Alternative Rock,US,169,20,10379297,Falling,Average,New
Poker Face,Lady Gaga,1275472,-64590,8736190,Pop,US,170,389,10011662,Falling,Average,Evergreen
Cruel Summer,Taylor Swift,1268541,9198,2527884,Pop,US,172,1014,3796425,Rising,Average,Evergreen
Boys Don't Cry,The Cure,1263767,15843,6006104,New Wave,GB,173,53,7269871,Rising,Average,Stable Hit
luther,Kendrick Lamar,1260494,-89450,9151667,Hip Hop,US,175,483,10412161,Falling,Average,Evergreen
What You Saying,Lil Uzi Vert,1259173,-27420,8754899,Rap,US,176,80,10014072,Falling,Average,Stable Hit
S&M,Rihanna,1257351,-87753,7352626,Pop,US,177,30,8609977,Falling,Average,New
No Pole,Don Toliver,1254541,-53350,9273774,Billboard Hot 100,US,178,454,10528315,Falling,Average,Evergreen
Last Friday Night (T.G.I.F.),Katy Perry,1251765,-19664,2523194,Pop,US,179,99,3774959,Falling,Average,Stable Hit
Just Keep Watching (From F1® The Movie) (w/ F1 The Album),Tate McRae,1245007,-77995,9035434,Dolby Atmos,CA,181,270,10280441,Falling,Average,Evergreen
Flashing Lights (w/ Dwele),Kanye West,1241168,-39451,8480893,Pop,GB,185,244,9722061,Falling,Average,Evergreen
Gangsta's Paradise (w/ L.V.),Coolio,1239884,-37552,4891917,Hip Hop,US,187,791,6131801,Falling,Average,Evergreen
nuts (w/ rainy bear),Lil Peep,1237223,-11727,4787172,Hip Hop,US,188,5,6024395,Falling,Average,New
Perfect,Ed Sheeran,1227709,-74196,8956978,Pop,GB,190,3070,10184687,Falling,Average,Evergreen
Summertime Sadness,Lana Del Rey,1227362,-104470,7508206,Indie Pop,US,191,1093,8735568,Falling,Average,Evergreen
Come As You Are - Remastered,Nirvana,1224750,-89453,6372663,Grunge,US,192,153,7597413,Falling,Average,Evergreen
Breakin' Dishes,Rihanna,1224675,-24245,8638532,Pop,US,193,346,9863207,Falling,Average,Evergreen
The Chain - 2004 Remaster,Fleetwood Mac,1210598,-79537,8817306,Rock,GB,196,205,10027904,Falling,Average,Evergreen
Love On The Brain,Rihanna,1203160,-69820,7439269,Soul,US,197,352,8642429,Falling,Average,Evergreen
Sign of the Times,Harry Styles,1198929,-121566,3816744,Pop,England,198,331,5015673,Falling,Average,Evergreen
Sorry,Justin Bieber,1192146,-86760,7346804,Pop,CA,199,767,8538950,Falling,Average,Evergreen
Life Goes On,BTS,1191777,-76127,8979038,K-Pop,KR,200,207,10170815,Falling,Average,Evergreen

In [135]:
import importlib
import data_standardization

importlib.reload(data_standardization)

from data_standardization import subgenre_to_main_genre

pd.set_option('display.max_rows', 500)
country_df = spotify_dtb_df[['genre']]
spotify_dtb_df['genre'] = spotify_dtb_df['genre'].apply(subgenre_to_main_genre)
spotify_dtb_df[['genre']]

# Rename Incorrect casing of names
spotify_dtb_df.loc['The Visitor', 'artist'] = 'Sienna Spiro'
spotify_dtb_df.loc['Si Antes Te Hubiera Conocido', 'artist'] = 'Karol G'

In [136]:
spotify_dtb_df[['popularity_category']].iloc[0:101]

                                                   popularity_category
track_name
SWIM                                                          Trending
Body to Body                                                  Trending
Babydoll                                                      Trending
Hooligan                                                      Trending
FYA                                                           Trending
NORMAL                                                         Average
Stateside + Zara Larsson (w/ Zara Larsson)                     Average
Aliens                                                         Average
2                                                              Average
Like Animals                                                   Average
Merry Go Round                                                 Average
they don’t know ’bout us                                       Average
Man I Need                                                     Average
DtMF                                                           Average
End of Beginning                                               Average
Risk It All                                                    Average
One More Night                                                 Average
So Easy (To Fall In Love)                                      Average
Please                                                         Average
Raindance (w/ Tems)                                            Average
No. 29                                                         Average
Into the Sun                                                   Average
The Fate of Ophelia                                            Average
back to friends                                                Average
BAILE INoLVIDABLE                                              Average
Lush Life                                                      Average
WHERE IS MY HUSBAND!                                           Average
NUEVAYoL                                                       Average
American Girls                                                 Average
iloveitiloveitiloveit                                          Average
I Just Might                                                   Average
Iris                                                           Average
Die With A Smile (w/ Bruno Mars)                               Average
Manchild                                                       Average
Tití Me Preguntó                                               Average
Love Me Not                                                    Average
EoO                                                            Average
White Keys                                                     Average
BIRDS OF A FEATHER                                             Average
Die On This Hill                                               Average
Every Breath You Take                                          Average
Dracula - JENNIE Remix (w/ JENNIE)                             Average
12 to 12                                                       Average
Mr. Brightside                                                 Average
Espresso                                                       Average
Choosin' Texas                                                 Average
I Thought I Saw Your Face Today                                Average
(When You Gonna) Give It Up to Me (w/ Keyshia C...             Average
Homewrecker                                                    Average
Sailor Song                                                    Average
Beautiful Things                                               Average
Sweater Weather                                                Average
One Dance (w/ Wizkid, Kyla)                                    Average
Rein Me In (w/ Olivia Dean)                                    Average
Creep                                                          Average
Opalite                                                        Average
FEVER DREAM                                                    Average
dopamina (w/ Tito Double P)                                    Average
E85                                                            Average
That's What I Like                                             Average
Dracula                                                        Average
Dreams - 2004 Remaster                                         Average
Gabriela                                                       Average
Yellow                                                         Average
Locked out of Heaven                                           Average
I Wanna Be Yours                                               Average
Who                                                            Average
VOY A LLeVARTE PA PR                                           Average
daño (w/ Tito Double P)                                        Average
Starboy (w/ Daft Punk)                                         Average
Lose Control                                                   Average
Riptide                                                        Average
WILDFLOWER                                                     Average
LA CANCIÓN (w/ Bad Bunny)                                      Average
Qué Pasaría... (w/ Bad Bunny)                                  Average
Feel Good Inc                                                  Average
All The Stars (w/ SZA)                                         Average
See You Again (w/ Kali Uchis)                                  Average
In the End                                                     Average
One Of The Girls (w/ JENNIE, Lily-Rose Depp)                   Average
Danza Kuduro (w/ Lucenzo)                                      Average
Aperture                                                       Average
La Plena - W Sound 05 (w/ Beéle, Ovy On The Drums)             Average
LA VILLA (w/ Kapo, Gangsta)                                    Average
Good Luck, Babe!                                               Average
Viva La Vida                                                   Average
As It Was                                                      Average
We Are The People                                              Average
The Less I Know The Better                                     Average
505                                                            Average
Seven (w/ Latto)                                               Average
Marlboro Rojo                                                  Average
Todo Lo Fue                                                    Average
The Visitor                                                    Average
Billie Jean                                                    Average
Si Antes Te Hubiera Conocido                                   Average
Pvta Luna                                                      Average
Ya Borracho                                                    Average
undressed                                                      Average
Shape of You                                                   Average
That’s So True                                                 Average

In [137]:
spotify_dtb_df[['streams', 'stream_change', 'streams_7day']]

,streams,stream_change,streams_7day
track_name,,,
SWIM,11273830,-3370522,25918182
Body to Body,6815694,-4369341,18000729
Babydoll,5733862,178968,36599831
Hooligan,5338608,-3396855,14074071
FYA,5196767,-2873904,13267438
NORMAL,4749288,-2410388,11908964
Stateside + Zara Larsson (w/ Zara Larsson),4738329,-235112,34238168
Aliens,4718569,-3036604,12473742
2,4573989,-2809104,11957082
Like Animals,4567309,-2259887,11394505
Merry Go Round,4490039,-2740868,11720946
they don’t know ’bout us,4423675,-2305775,11153125
Man I Need,4300853,-86237,28683798
DtMF,4274742,-111657,29551375
End of Beginning,4108838,51706,27783861
Risk It All,4007478,-499146,31739152
One More Night,3979999,-2153273,10113271
So Easy (To Fall In Love),3932082,33687,27406397
Please,3897341,-2024958,9819640
Raindance (w/ Tems),3876044,-197505,25945780
No. 29,3769141,-2733812,10272094
Into the Sun,3766459,-1959266,9492184
The Fate of Ophelia,3721332,-164240,26075129
back to friends,3583316,-131585,25787563
BAILE INoLVIDABLE,3344867,-44475,22663387
Lush Life,3341957,-21457,21857968
WHERE IS MY HUSBAND!,3241010,5314,22068930
NUEVAYoL,3221298,-80099,21951925
American Girls,3101460,-420059,24771218
iloveitiloveitiloveit,2978129,-293545,22515039
I Just Might,2860193,-16107,19846361
Iris,2776320,-126309,19907609
Die With A Smile (w/ Bruno Mars),2691880,-142292,19325340
Manchild,2649376,-38989,17388953
Tití Me Preguntó,2649180,-7253,17660827
Love Me Not,2547681,-24120,17684406
EoO,2542905,-123890,17968199
White Keys,2531236,-178737,17360808
BIRDS OF A FEATHER,2529075,24180,17056445
Die On This Hill,2398309,-322885,19212395
Every Breath You Take,2367833,25446,16070168
Dracula - JENNIE Remix (w/ JENNIE),2332341,-89323,15767565
12 to 12,2260402,-86182,15853606
Mr. Brightside,2220784,-28156,14355698
Espresso,2213750,90339,13566149
Choosin' Texas,2169091,10331,13900513
I Thought I Saw Your Face Today,2155500,-138406,15647967
(When You Gonna) Give It Up to Me (w/ Keyshia Cole),2154338,-112939,14951009
Homewrecker,2139700,-220893,15402927
Sailor Song,2107410,-121996,16461691
Beautiful Things,2090231,129461,13021976
Sweater Weather,2068795,-177998,15845100
"One Dance (w/ Wizkid, Kyla)",2035423,-105895,13481976
Rein Me In (w/ Olivia Dean),2020602,-34643,12610414
Creep,2011657,-91449,14176633
Opalite,1992549,-70008,14093798
FEVER DREAM,1992250,-130117,13935046
dopamina (w/ Tito Double P),1952764,66159,12629601
E85,1948495,-127853,13479304
That's What I Like,1912383,-142486,12699826
Dracula,1906471,-84531,13354497
Dreams - 2004 Remaster,1894536,109844,11986886
Gabriela,1850006,60664,12468922
Yellow,1828666,-99526,12862160
Locked out of Heaven,1827015,-180903,13448378
I Wanna Be Yours,1825413,-80003,13563046
Who,1807214,176731,11524586
VOY A LLeVARTE PA PR,1780848,-133648,12359622
daño (w/ Tito Double P),1780764,34375,11510694
Starboy (w/ Daft Punk),1761445,-119116,12541479
Lose Control,1737868,29374,11380332
Riptide,1737857,-5537,11544093
WILDFLOWER,1730195,-201850,13900491
LA CANCIÓN (w/ Bad Bunny),1708412,3072,11498926
Qué Pasaría... (w/ Bad Bunny),1674168,25719,11406360
Feel Good Inc,1669648,-99808,11921501
All The Stars (w/ SZA),1665602,-10997,11456499
See You Again (w/ Kali Uchis),1662229,73090,10586720
In the End,1647656,-111701,11401354
"One Of The Girls (w/ JENNIE, Lily-Rose Depp)",1643774,-137154,12741548
Danza Kuduro (w/ Lucenzo),1643700,-105775,10737763
Aperture,1643576,-159524,13195579
"La Plena - W Sound 05 (w/ Beéle, Ovy On The Drums)",1639753,-17075,10668572
"LA VILLA (w/ Kapo, Gangsta)",1634806,64909,10801896
"Good Luck, Babe!",1621060,15852,10803226
Viva La Vida,1610233,106290,10117917
As It Was,1608775,-150504,11660629
We Are The People,1594097,-30037,11149329
The Less I Know The Better,1593781,-51333,10870662
505,1587695,-113645,11653237
Seven (w/ Latto),1580746,-80854,11202875
Marlboro Rojo,1564019,112870,10014833
Todo Lo Fue,1563733,90601,10043908
The Visitor,1558344,-296012,12044907
Billie Jean,1551069,20972,9991848
Si Antes Te Hubiera Conocido,1540953,46742,9623813
Pvta Luna,1537690,56324,10293259
Ya Borracho,1536251,49704,9999127
undressed,1535615,-88400,10972970
Shape of You,1532739,-41473,10263688
That’s So True,1526228,-51917,10719195
Midnight Sun,1512185,-10911,10133254
When I Was Your Man,1508958,144568,10366342
Have You Ever Seen The Rain,1507387,52997,9344647
Sparks,1504857,-3015,10932582
COQUETA (w/ Grupo Frontera),1503126,62199,9876432
Somewhere Only We Know,1496326,10006,10165562
Taste Back,1480809,-206276,12746602
Zoo (w/ Shakira),1466813,189999,4001191
Smells Like Teen Spirit - Remastered,1453513,-125183,10271555
Blinding Lights,1448450,11224,9729402
7-3 (w/ Tito Double P),1440677,5573,9736835
Porch Light,1430611,-374516,12359863
Just the Way You Are,1423798,-102703,10482326
Coming Up Roses,1418986,-230104,12650537
Nice To Each Other,1416007,-50721,9872551
Counting Stars,1414383,-31879,9525522
Fame is a Gun,1404894,-2613,10047427
Only Girl (In The World),1398296,-52230,9276305
Bring Me To Life,1396427,-131213,10205781
Don't Stop The Music,1395227,-40325,9282714
Timeless (w/ Playboi Carti),1392146,-94943,10349253
Promiscuous (w/ Timbaland),1390532,-5054,8860680
"Give Me Everything (w/ Ne-Yo, AFROJACK, Nayer)",1389531,-110927,9497950
"chiclona (w/ Tito Double P, LENCHO)",1389411,-12742,9202643
no tiene sentido,1380148,-55381,9480736
Kiss It Better,1379747,-223043,10359276
Body,1377373,-100397,10001871
The Night We Met,1368186,-94429,10515041
Sweet Child O' Mine,1367839,-13859,8983873
Let Me Love You (w/ Justin Bieber),1364636,-88823,10084292
Numb,1350782,-120313,9629438
Africa,1350745,-23426,7537107
Who Knows,1349819,-151500,10486538
The Man Who Can't Be Moved,1349075,-126873,10424946
A Couple Minutes,1348112,-57009,9770863
Everybody Wants To Rule The World,1345799,28946,6232525
No One Noticed,1342468,-53818,10132311
Without Me,1335886,-100932,9154300
Hips Don't Lie (w/ Wyclef Jean),1330852,24927,6218904
Me Rehúso,1326162,-38797,8914757
"VeLDÁ (w/ Omar Courtz, Dei V)",1326149,-90827,9468025
Style,1311077,-73973,8934698
Payphone (w/ Wiz Khalifa),1306200,-28788,9226178
Please Please Please,1296957,-1727,5009467
TU SANCHO,1296297,19803,8708123
Shut up My Moms Calling,1294677,-8737,9158699
"Ready, Steady, Go!",1294001,-190275,11338844
We Found Love (w/ Calvin Harris),1292535,-110188,7904030
Sex on Fire,1290404,5746,3835428
Wonderwall - Remastered,1286520,-64148,8821556
Too Sweet,1283948,40456,6149401
"Can't Hold Us (w/ Macklemore, Ryan Lewis, Ray Dalton)",1282248,-87604,8781747
DAISIES,1281664,-20169,8990092
Sunflower - Spider-Man: Into the Spider-Verse (w/ Swae Lee),1281251,-6790,5025791
Take on Me - 2015 Remaster,1279646,-21334,4937908
Can't Stop - 2014 Remaster,1275766,-114450,9103531
Poker Face,1275472,-64590,8736190
Cruel Summer,1268541,9198,2527884
Boys Don't Cry,1263767,15843,6006104
luther,1260494,-89450,9151667
What You Saying,1259173,-27420,8754899
S&M,1257351,-87753,7352626
No Pole,1254541,-53350,9273774
Last Friday Night (T.G.I.F.),1251765,-19664,2523194
Just Keep Watching (From F1® The Movie) (w/ F1 The Album),1245007,-77995,9035434
Flashing Lights (w/ Dwele),1241168,-39451,8480893
Gangsta's Paradise (w/ L.V.),1239884,-37552,4891917
nuts (w/ rainy bear),1237223,-11727,4787172
Perfect,1227709,-74196,8956978
Summertime Sadness,1227362,-104470,7508206
Come As You Are - Remastered,1224750,-89453,6372663
Breakin' Dishes,1224675,-24245,8638532
The Chain - 2004 Remaster,1210598,-79537,8817306
Love On The Brain,1203160,-69820,7439269
Sign of the Times,1198929,-121566,3816744
Sorry,1192146,-86760,7346804
Life Goes On,1191777,-76127,8979038

In [138]:
spotify_dtb_df[['days_on_chart', 'longevity']]

highest_stable = spotify_dtb_df[spotify_dtb_df['longevity'] == 'Stable Hit']['days_on_chart'].max()
print(highest_stable)
lowest_evergreen = spotify_dtb_df[spotify_dtb_df['longevity'] == 'Evergreen']['days_on_chart'].min()
print(lowest_evergreen)

print(spotify_dtb_df['longevity'].unique())

from data_standardization import categorize_longevity
spotify_dtb_df['longevity'] = spotify_dtb_df['days_on_chart'].apply(categorize_longevity)
spotify_dtb_df[['days_on_chart', 'longevity']]

99
102
['New' 'Evergreen' 'Stable Hit']

                                                    days_on_chart   longevity
track_name
SWIM                                                            2         New
Body to Body                                                    2         New
Babydoll                                                      119   Evergreen
Hooligan                                                        2         New
FYA                                                             2         New
NORMAL                                                          2         New
Stateside + Zara Larsson (w/ Zara Larsson)                     74  Stable Hit
Aliens                                                          2         New
2                                                               2         New
Like Animals                                                    2         New
Merry Go Round                                                  2         New
they don’t know ’bout us                                        2         New
Man I Need                                                    214   Evergreen
DtMF                                                          441   Evergreen
End of Beginning                                              764   Evergreen
Risk It All                                                    23         New
One More Night                                                  2         New
So Easy (To Fall In Love)                                     176   Evergreen
Please                                                          2         New
Raindance (w/ Tems)                                           109   Evergreen
No. 29                                                          2         New
Into the Sun                                                    2         New
The Fate of Ophelia                                           170   Evergreen
back to friends                                               369   Evergreen
BAILE INoLVIDABLE                                             441   Evergreen
Lush Life                                                     761   Evergreen
WHERE IS MY HUSBAND!                                          184   Evergreen
NUEVAYoL                                                      441   Evergreen
American Girls                                                 16         New
iloveitiloveitiloveit                                          30         New
I Just Might                                                   72  Stable Hit
Iris                                                          919   Evergreen
Die With A Smile (w/ Bruno Mars)                              583   Evergreen
Manchild                                                      289   Evergreen
Tití Me Preguntó                                              483   Evergreen
Love Me Not                                                   368   Evergreen
EoO                                                           437   Evergreen
White Keys                                                     28         New
BIRDS OF A FEATHER                                            674   Evergreen
Die On This Hill                                              102   Evergreen
Every Breath You Take                                        1619   Evergreen
Dracula - JENNIE Remix (w/ JENNIE)                             36  Stable Hit
12 to 12                                                      236   Evergreen
Mr. Brightside                                               1682   Evergreen
Espresso                                                      709   Evergreen
Choosin' Texas                                                 80  Stable Hit
I Thought I Saw Your Face Today                               104   Evergreen
(When You Gonna) Give It Up to Me (w/ Keyshia C...             65  Stable Hit
Homewrecker                                                    44  Stable Hit
Sailor Song                                                   581   Evergreen
Beautiful Things                                              793   Evergreen
Sweater Weather                                              2120   Evergreen
One Dance (w/ Wizkid, Kyla)                                  2135   Evergreen
Rein Me In (w/ Olivia Dean)                                    23         New
Creep                                                         842   Evergreen
Opalite                                                       170   Evergreen
FEVER DREAM                                                    23         New
dopamina (w/ Tito Double P)                                    86  Stable Hit
E85                                                            51  Stable Hit
That's What I Like                                           1254   Evergreen
Dracula                                                       138   Evergreen
Dreams - 2004 Remaster                                       1004   Evergreen
Gabriela                                                      275   Evergreen
Yellow                                                       1909   Evergreen
Locked out of Heaven                                         1548   Evergreen
I Wanna Be Yours                                             1354   Evergreen
Who                                                           611   Evergreen
VOY A LLeVARTE PA PR                                          375   Evergreen
daño (w/ Tito Double P)                                        86  Stable Hit
Starboy (w/ Daft Punk)                                       2095   Evergreen
Lose Control                                                  856   Evergreen
Riptide                                                      2586   Evergreen
WILDFLOWER                                                    674   Evergreen
LA CANCIÓN (w/ Bad Bunny)                                     988   Evergreen
Qué Pasaría... (w/ Bad Bunny)                                 427   Evergreen
Feel Good Inc                                                 443   Evergreen
All The Stars (w/ SZA)                                       1016   Evergreen
See You Again (w/ Kali Uchis)                                1066   Evergreen
In the End                                                   1012   Evergreen
One Of The Girls (w/ JENNIE, Lily-Rose Depp)                  896   Evergreen
Danza Kuduro (w/ Lucenzo)                                     802   Evergreen
Aperture                                                       58  Stable Hit
La Plena - W Sound 05 (w/ Beéle, Ovy On The Drums)            389   Evergreen
LA VILLA (w/ Kapo, Gangsta)                                    75  Stable Hit
Good Luck, Babe!                                              710   Evergreen
Viva La Vida                                                 1329   Evergreen
As It Was                                                    1401   Evergreen
We Are The People                                             242   Evergreen
The Less I Know The Better                                    510   Evergreen
505                                                          1537   Evergreen
Seven (w/ Latto)                                              981   Evergreen
Marlboro Rojo                                                 317   Evergreen
Todo Lo Fue                                                    58  Stable Hit
The Visitor                                                     9         New
Billie Jean                                                   363   Evergreen
Si Antes Te Hubiera Conocido                                  583   Evergreen
Pvta Luna                                                     127   Evergreen
Ya Borracho                                                   122   Evergreen
undressed                                                     358   Evergreen
Shape of You                                                 2815   Evergreen
That’s So True                                                519   Evergreen
Midnight Sun                                                   63  Stable Hit
When I Was Your Man                                          1476   Evergreen
Have You Ever Seen The Rain                                   484   Evergreen
Sparks                                                        562   Evergreen
COQUETA (w/ Grupo Frontera)                                   309   Evergreen
Somewhere Only We Know                                       1193   Evergreen
Taste Back                                                     16         New
Zoo (w/ Shakira)                                               58  Stable Hit
Smells Like Teen Spirit - Remastered                          727   Evergreen
Blinding Lights                                              2301   Evergreen
7-3 (w/ Tito Double P)                                         86  Stable Hit
Porch Light                                                     9         New
Just the Way You Are                                         1197   Evergreen
Coming Up Roses                                                16         New
Nice To Each Other                                            212   Evergreen
Counting Stars                                               2495   Evergreen
Fame is a Gun                                                 120   Evergreen
Only Girl (In The World)                                      131   Evergreen
Bring Me To Life                                              341   Evergreen
Don't Stop The Music                                          117   Evergreen
Timeless (w/ Playboi Carti)                                   541   Evergreen
Promiscuous (w/ Timbaland)                                    171   Evergreen
Give Me Everything (w/ Ne-Yo, AFROJACK, Nayer)                511   Evergreen
chiclona (w/ Tito Double P, LENCHO)                            21         New
no tiene sentido                                              287   Evergreen
Kiss It Better                                                142   Evergreen
Body                                                           51  Stable Hit
The Night We Met                                             1327   Evergreen
Sweet Child O' Mine                                           440   Evergreen
Let Me Love You (w/ Justin Bieber)                            809   Evergreen
Numb                                                          704   Evergreen
Africa                                                        753   Evergreen
Who Knows                                                     120   Evergreen
The Man Who Can't Be Moved                                    157   Evergreen
A Couple Minutes                                              118   Evergreen
Everybody Wants To Rule The World                            1027   Evergreen
No One Noticed                                                496   Evergreen
Without Me                                                   1637   Evergreen
Hips Don't Lie (w/ Wyclef Jean)                               338   Evergreen
Me Rehúso                                                     617   Evergreen
VeLDÁ (w/ Omar Courtz, Dei V)                                 395   Evergreen
Style                                                         347   Evergreen
Payphone (w/ Wiz Khalifa)                                     712   Evergreen
Please Please Please                                          503   Evergreen
TU SANCHO                                                     284   Evergreen
Shut up My Moms Calling                                       773   Evergreen
Ready, Steady, Go!                                             16         New
We Found Love (w/ Calvin Harris)                              823   Evergreen
Sex on Fire                                                    63  Stable Hit
Wonderwall - Remastered                                       884   Evergreen
Too Sweet                                                     620   Evergreen
Can't Hold Us (w/ Macklemore, Ryan Lewis, Ray D...           1211   Evergreen
DAISIES                                                       252   Evergreen
Sunflower - Spider-Man: Into the Spider-Verse (...           2292   Evergreen
Take on Me - 2015 Remaster                                     14         New
Can't Stop - 2014 Remaster                                     20         New
Poker Face                                                    389   Evergreen
Cruel Summer                                                 1014   Evergreen
Boys Don't Cry                                                 53  Stable Hit
luther                                                        483   Evergreen
What You Saying                                                80  Stable Hit
S&M                                                            30         New
No Pole                                                       454   Evergreen
Last Friday Night (T.G.I.F.)                                   99  Stable Hit
Just Keep Watching (From F1® The Movie) (w/ F1 ...            270   Evergreen
Flashing Lights (w/ Dwele)                                    244   Evergreen
Gangsta's Paradise (w/ L.V.)                                  791   Evergreen
nuts (w/ rainy bear)                                            5         New
Perfect                                                      3070   Evergreen
Summertime Sadness                                           1093   Evergreen
Come As You Are - Remastered                                  153   Evergreen
Breakin' Dishes                                               346   Evergreen
The Chain - 2004 Remaster                                     205   Evergreen
Love On The Brain                                             352   Evergreen
Sign of the Times                                             331   Evergreen
Sorry                                                         767   Evergreen
Life Goes On                                                  207   Evergreen

In [139]:
spotify_dtb_df[['country']]
spotify_dtb_df['country'].unique()

import importlib
import data_standardization

importlib.reload(data_standardization)

from data_standardization import country_domain_to_fullname_country

spotify_dtb_df['country'] = spotify_dtb_df['country'].apply(country_domain_to_fullname_country)

spotify_dtb_df[['country']]

                                                           country
track_name
SWIM                                                   South Korea
Body to Body                                           South Korea
Babydoll                                             United States
Hooligan                                               South Korea
FYA                                                    South Korea
NORMAL                                                 South Korea
Stateside + Zara Larsson (w/ Zara Larsson)          United Kingdom
Aliens                                                 South Korea
2                                                      South Korea
Like Animals                                           South Korea
Merry Go Round                                         South Korea
they don’t know ’bout us                               South Korea
Man I Need                                           United States
DtMF                                                   Puerto Rico
End of Beginning                                     United States
Risk It All                                          United States
One More Night                                         South Korea
So Easy (To Fall In Love)                            United States
Please                                                 South Korea
Raindance (w/ Tems)                                  United States
No. 29                                                 South Korea
Into the Sun                                           South Korea
The Fate of Ophelia                                  United States
back to friends                                      United States
BAILE INoLVIDABLE                                      Puerto Rico
Lush Life                                                   Sweden
WHERE IS MY HUSBAND!                                United Kingdom
NUEVAYoL                                               Puerto Rico
American Girls                                      United Kingdom
iloveitiloveitiloveit                                United States
I Just Might                                         United States
Iris                                                 United States
Die With A Smile (w/ Bruno Mars)                     United States
Manchild                                             United States
Tití Me Preguntó                                       Puerto Rico
Love Me Not                                          United States
EoO                                                    Puerto Rico
White Keys                                           United States
BIRDS OF A FEATHER                                   United States
Die On This Hill                                    United Kingdom
Every Breath You Take                               United Kingdom
Dracula - JENNIE Remix (w/ JENNIE)                       Australia
12 to 12                                             United States
Mr. Brightside                                      United Kingdom
Espresso                                             United States
Choosin' Texas                                       United States
I Thought I Saw Your Face Today                      United States
(When You Gonna) Give It Up to Me (w/ Keyshia C...         Jamaica
Homewrecker                                          United States
Sailor Song                                                  Italy
Beautiful Things                                     United States
Sweater Weather                                     United Kingdom
One Dance (w/ Wizkid, Kyla)                                 Canada
Rein Me In (w/ Olivia Dean)                         United Kingdom
Creep                                               United Kingdom
Opalite                                              United States
FEVER DREAM                                         United Kingdom
dopamina (w/ Tito Double P)                                 Mexico
E85                                                  United States
That's What I Like                                   United States
Dracula                                                  Australia
Dreams - 2004 Remaster                              United Kingdom
Gabriela                                             United States
Yellow                                              United Kingdom
Locked out of Heaven                                 United States
I Wanna Be Yours                                    United Kingdom
Who                                                    South Korea
VOY A LLeVARTE PA PR                                   Puerto Rico
daño (w/ Tito Double P)                                     Mexico
Starboy (w/ Daft Punk)                                      Canada
Lose Control                                         United States
Riptide                                                  Australia
WILDFLOWER                                           United States
LA CANCIÓN (w/ Bad Bunny)                                 Colombia
Qué Pasaría... (w/ Bad Bunny)                          Puerto Rico
Feel Good Inc                                       United Kingdom
All The Stars (w/ SZA)                               United States
See You Again (w/ Kali Uchis)                        United States
In the End                                           United States
One Of The Girls (w/ JENNIE, Lily-Rose Depp)                Canada
Danza Kuduro (w/ Lucenzo)                              Puerto Rico
Aperture                                            United Kingdom
La Plena - W Sound 05 (w/ Beéle, Ovy On The Drums)           Japan
LA VILLA (w/ Kapo, Gangsta)                          United States
Good Luck, Babe!                                     United States
Viva La Vida                                        United Kingdom
As It Was                                           United Kingdom
We Are The People                                        Australia
The Less I Know The Better                               Australia
505                                                 United Kingdom
Seven (w/ Latto)                                       South Korea
Marlboro Rojo                                               Mexico
Todo Lo Fue                                                 Mexico
The Visitor                                         United Kingdom
Billie Jean                                          United States
Si Antes Te Hubiera Conocido                              Colombia
Pvta Luna                                                   Mexico
Ya Borracho                                                 Mexico
undressed                                            United States
Shape of You                                        United Kingdom
That’s So True                                       United States
Midnight Sun                                                Sweden
When I Was Your Man                                  United States
Have You Ever Seen The Rain                          United States
Sparks                                              United Kingdom
COQUETA (w/ Grupo Frontera)                                 Mexico
Somewhere Only We Know                              United Kingdom
Taste Back                                          United Kingdom
Zoo (w/ Shakira)                                     United States
Smells Like Teen Spirit - Remastered                 United States
Blinding Lights                                             Canada
7-3 (w/ Tito Double P)                                      Mexico
Porch Light                                          United States
Just the Way You Are                                 United States
Coming Up Roses                                     United Kingdom
Nice To Each Other                                   United States
Counting Stars                                       United States
Fame is a Gun                                        United States
Only Girl (In The World)                             United States
Bring Me To Life                                     United States
Don't Stop The Music                                 United States
Timeless (w/ Playboi Carti)                                 Canada
Promiscuous (w/ Timbaland)                                  Canada
Give Me Everything (w/ Ne-Yo, AFROJACK, Nayer)       United States
chiclona (w/ Tito Double P, LENCHO)                         Mexico
no tiene sentido                                          Colombia
Kiss It Better                                       United States
Body                                                 United States
The Night We Met                                     United States
Sweet Child O' Mine                                  United States
Let Me Love You (w/ Justin Bieber)                          France
Numb                                                 United States
Africa                                               United States
Who Knows                                                   Canada
The Man Who Can't Be Moved                          United Kingdom
A Couple Minutes                                     United States
Everybody Wants To Rule The World                   United Kingdom
No One Noticed                                      United Kingdom
Without Me                                           United States
Hips Don't Lie (w/ Wyclef Jean)                           Colombia
Me Rehúso                                            United States
VeLDÁ (w/ Omar Courtz, Dei V)                          Puerto Rico
Style                                                United States
Payphone (w/ Wiz Khalifa)                            United States
Please Please Please                                 United States
TU SANCHO                                                   Mexico
Shut up My Moms Calling                              United States
Ready, Steady, Go!                                  United Kingdom
We Found Love (w/ Calvin Harris)                     United States
Sex on Fire                                          United States
Wonderwall - Remastered                             United Kingdom
Too Sweet                                                  Ireland
Can't Hold Us (w/ Macklemore, Ryan Lewis, Ray D...   United States
DAISIES                                                     Canada
Sunflower - Spider-Man: Into the Spider-Verse (...   United States
Take on Me - 2015 Remaster                                  Norway
Can't Stop - 2014 Remaster                           United States
Poker Face                                           United States
Cruel Summer                                         United States
Boys Don't Cry                                      United Kingdom
luther                                               United States
What You Saying                                      United States
S&M                                                  United States
No Pole                                              United States
Last Friday Night (T.G.I.F.)                         United States
Just Keep Watching (From F1® The Movie) (w/ F1 ...          Canada
Flashing Lights (w/ Dwele)                          United Kingdom
Gangsta's Paradise (w/ L.V.)                         United States
nuts (w/ rainy bear)                                 United States
Perfect                                             United Kingdom
Summertime Sadness                                   United States
Come As You Are - Remastered                         United States
Breakin' Dishes                                      United States
The Chain - 2004 Remaster                           United Kingdom
Love On The Brain                                    United States
Sign of the Times                                   United Kingdom
Sorry                                                       Canada
Life Goes On                                           South Korea

In [140]:
spotify_dtb_df

uncategorized_genre = spotify_dtb_df.loc[spotify_dtb_df['genre'] == 'Uncategorized', 'genre']

uncategorized_genre

track_name
Stateside + Zara Larsson (w/ Zara Larsson)                   Uncategorized
iloveitiloveitiloveit                                        Uncategorized
EoO                                                          Uncategorized
E85                                                          Uncategorized
Marlboro Rojo                                                Uncategorized
Zoo (w/ Shakira)                                             Uncategorized
Body                                                         Uncategorized
Who Knows                                                    Uncategorized
Me Rehúso                                                    Uncategorized
TU SANCHO                                                    Uncategorized
No Pole                                                      Uncategorized
Just Keep Watching (From F1® The Movie) (w/ F1 The Album)    Uncategorized
Name: genre, dtype: object

In [ ]:
spotify_dtb_df.loc['iloveitiloveitiloveit', 'genre'] = 'Pop'
spotify_dtb_df.loc['EoO', 'genre'] = 'Latin'
spotify_dtb_df.loc['E85', 'genre'] = 'Hip Hop'
spotify_dtb_df.loc['Marlboro Rojo', 'genre'] = 'Latin'
spotify_dtb_df.loc['Zoo (w/ Shakira)', 'genre'] = 'Pop'
spotify_dtb_df.loc['Body', 'genre'] = 'Hip Hop'
spotify_dtb_df.loc['Who Knows', 'genre'] = 'R&B'
spotify_dtb_df.loc['Me Rehúso', 'genre'] = 'Latin'
spotify_dtb_df.loc['TU SANCHO', 'genre'] = 'Latin'
spotify_dtb_df.loc['No Pole', 'genre'] = 'Hip Hop'
spotify_dtb_df.loc['Just Keep Watching (From F1® The Movie) (w/ F1 The Album)', 'genre'] = 'Pop'
spotify_dtb_df.loc['Stateside + Zara Larsson (w/ Zara Larsson)', 'genre'] = 'Pop'
spotify_dtb_df.loc['Just Keep Watching (From F1® The Movie) (w/ F1 The Album)', 'genre'] = 'Pop'

import importlib
import data_standardization

importlib.reload(data_standardization)
spotify_dtb_df

,artist,streams,stream_change,streams_7day,genre,country,position,days_on_chart,viral_score,trend,popularity_category,longevity
track_name,,,,,,,,,,,,
SWIM,BTS,11273830,-3370522,25918182,Pop,South Korea,1,2,37192012,Falling,Trending,New
Body to Body,BTS,6815694,-4369341,18000729,Pop,South Korea,2,2,24816423,Falling,Trending,New
Babydoll,Dominic Fike,5733862,178968,36599831,Pop,United States,3,119,42333693,Rising,Trending,Evergreen
Hooligan,BTS,5338608,-3396855,14074071,Pop,South Korea,4,2,19412679,Falling,Trending,New
FYA,BTS,5196767,-2873904,13267438,Pop,South Korea,5,2,18464205,Falling,Trending,New
NORMAL,BTS,4749288,-2410388,11908964,Pop,South Korea,6,2,16658252,Falling,Average,New
Stateside + Zara Larsson (w/ Zara Larsson),PinkPantheress,4738329,-235112,34238168,Uncategorized,United Kingdom,7,74,38976497,Falling,Average,Stable Hit
Aliens,BTS,4718569,-3036604,12473742,Pop,South Korea,8,2,17192311,Falling,Average,New
2,BTS,4573989,-2809104,11957082,Pop,South Korea,9,2,16531071,Falling,Average,New
Like Animals,BTS,4567309,-2259887,11394505,Pop,South Korea,10,2,15961814,Falling,Average,New
Merry Go Round,BTS,4490039,-2740868,11720946,Pop,South Korea,11,2,16210985,Falling,Average,New
they don’t know ’bout us,BTS,4423675,-2305775,11153125,Pop,South Korea,12,2,15576800,Falling,Average,New
Man I Need,Olivia Dean,4300853,-86237,28683798,Pop,United States,13,214,32984651,Falling,Average,Evergreen
DtMF,Bad Bunny,4274742,-111657,29551375,Pop,Puerto Rico,14,441,33826117,Falling,Average,Evergreen
End of Beginning,Djo,4108838,51706,27783861,Pop,United States,15,764,31892699,Rising,Average,Evergreen
Risk It All,Bruno Mars,4007478,-499146,31739152,Offizielle Charts,United States,16,23,35746630,Falling,Average,New
One More Night,BTS,3979999,-2153273,10113271,Pop,South Korea,17,2,14093270,Falling,Average,New
So Easy (To Fall In Love),Olivia Dean,3932082,33687,27406397,Pop,United States,18,176,31338479,Rising,Average,Evergreen
Please,BTS,3897341,-2024958,9819640,Pop,South Korea,19,2,13716981,Falling,Average,New
Raindance (w/ Tems),Dave,3876044,-197505,25945780,Hip Hop,United States,20,109,29821824,Falling,Average,Evergreen
No. 29,BTS,3769141,-2733812,10272094,Pop,South Korea,21,2,14041235,Falling,Average,New
Into the Sun,BTS,3766459,-1959266,9492184,Pop,South Korea,22,2,13258643,Falling,Average,New
The Fate of Ophelia,Taylor Swift,3721332,-164240,26075129,Pop,United States,23,170,29796461,Falling,Average,Evergreen
back to friends,sombr,3583316,-131585,25787563,Pop,United States,25,369,29370879,Falling,Average,Evergreen
BAILE INoLVIDABLE,Bad Bunny,3344867,-44475,22663387,Latin,Puerto Rico,26,441,26008254,Falling,Average,Evergreen
Lush Life,Zara Larsson,3341957,-21457,21857968,Pop,Sweden,27,761,25199925,Falling,Average,Evergreen
WHERE IS MY HUSBAND!,RAYE,3241010,5314,22068930,Pop,United Kingdom,28,184,25309940,Rising,Average,Evergreen
NUEVAYoL,Bad Bunny,3221298,-80099,21951925,Latin,Puerto Rico,29,441,25173223,Falling,Average,Evergreen
American Girls,Harry Styles,3101460,-420059,24771218,Rock,United Kingdom,31,16,27872678,Falling,Average,New
iloveitiloveitiloveit,Bella Kay,2978129,-293545,22515039,Pop,United States,32,30,25493168,Falling,Average,New
I Just Might,Bruno Mars,2860193,-16107,19846361,Pop,United States,33,72,22706554,Falling,Average,Stable Hit
Iris,The Goo Goo Dolls,2776320,-126309,19907609,Rock,United States,34,919,22683929,Falling,Average,Evergreen
Die With A Smile (w/ Bruno Mars),Lady Gaga,2691880,-142292,19325340,Pop,United States,35,583,22017220,Falling,Average,Evergreen
Manchild,Sabrina Carpenter,2649376,-38989,17388953,Pop,United States,36,289,20038329,Falling,Average,Evergreen
Tití Me Preguntó,Bad Bunny,2649180,-7253,17660827,Latin,Puerto Rico,37,483,20310007,Falling,Average,Evergreen
Love Me Not,Ravyn Lenae,2547681,-24120,17684406,Pop,United States,38,368,20232087,Falling,Average,Evergreen
EoO,Bad Bunny,2542905,-123890,17968199,Latin,Puerto Rico,39,437,20511104,Falling,Average,Evergreen
White Keys,Dominic Fike,2531236,-178737,17360808,Offizielle Charts,United States,40,28,19892044,Falling,Average,New
BIRDS OF A FEATHER,Billie Eilish,2529075,24180,17056445,Pop,United States,41,674,19585520,Rising,Average,Evergreen
Die On This Hill,SIENNA SPIRO,2398309,-322885,19212395,Pop,United Kingdom,43,102,21610704,Falling,Average,Evergreen
Every Breath You Take,The Police,2367833,25446,16070168,Rock,United Kingdom,44,1619,18438001,Rising,Average,Evergreen
Dracula - JENNIE Remix (w/ JENNIE),Tame Impala,2332341,-89323,15767565,Rock,Australia,45,36,18099906,Falling,Average,Stable Hit
12 to 12,sombr,2260402,-86182,15853606,Pop,United States,46,236,18114008,Falling,Average,Evergreen
Mr. Brightside,The Killers,2220784,-28156,14355698,Rock,United Kingdom,47,1682,16576482,Falling,Average,Evergreen
Espresso,Sabrina Carpenter,2213750,90339,13566149,Pop,United States,48,709,15779899,Rising,Average,Evergreen
Choosin' Texas,Ella Langley,2169091,10331,13900513,Country,United States,49,80,16069604,Rising,Average,Stable Hit
I Thought I Saw Your Face Today,She & Him,2155500,-138406,15647967,Pop,United States,50,104,17803467,Falling,Average,Evergreen
(When You Gonna) Give It Up to Me (w/ Keyshia Cole),Sean Paul,2154338,-112939,14951009,Latin,Jamaica,51,65,17105347,Falling,Average,Stable Hit
Homewrecker,sombr,2139700,-220893,15402927,Pop,United States,52,44,17542627,Falling,Average,Stable Hit
Sailor Song,Gigi Perez,2107410,-121996,16461691,Electronic,Italy,53,581,18569101,Falling,Average,Evergreen
Beautiful Things,Benson Boone,2090231,129461,13021976,Pop,United States,54,793,15112207,Rising,Average,Evergreen
Sweater Weather,The Neighbourhood,2068795,-177998,15845100,Rock,United Kingdom,56,2120,17913895,Falling,Average,Evergreen
"One Dance (w/ Wizkid, Kyla)",Drake,2035423,-105895,13481976,Hip Hop,Canada,57,2135,15517399,Falling,Average,Evergreen
Rein Me In (w/ Olivia Dean),Sam Fender,2020602,-34643,12610414,Rock,United Kingdom,58,23,14631016,Falling,Average,New
Creep,Radiohead,2011657,-91449,14176633,Rock,United Kingdom,59,842,16188290,Falling,Average,Evergreen
Opalite,Taylor Swift,1992549,-70008,14093798,Pop,United States,60,170,16086347,Falling,Average,Evergreen
FEVER DREAM,Alex Warren,1992250,-130117,13935046,Offizielle Charts,United Kingdom,61,23,15927296,Falling,Average,New
dopamina (w/ Tito Double P),Peso Pluma,1952764,66159,12629601,Latin,Mexico,62,86,14582365,Rising,Average,Stable Hit
E85,Don Toliver,1948495,-127853,13479304,Hip Hop,United States,63,51,15427799,Falling,Average,Stable Hit
That's What I Like,Bruno Mars,1912383,-142486,12699826,Pop,United States,65,1254,14612209,Falling,Average,Evergreen
Dracula,Tame Impala,1906471,-84531,13354497,Pop,Australia,66,138,15260968,Falling,Average,Evergreen
Dreams - 2004 Remaster,Fleetwood Mac,1894536,109844,11986886,Rock,United Kingdom,67,1004,13881422,Rising,Average,Evergreen
Gabriela,KATSEYE,1850006,60664,12468922,Girl Group,United States,68,275,14318928,Rising,Average,Evergreen
Yellow,Coldplay,1828666,-99526,12862160,Rock,United Kingdom,69,1909,14690826,Falling,Average,Evergreen
Locked out of Heaven,Bruno Mars,1827015,-180903,13448378,Pop,United States,70,1548,15275393,Falling,Average,Evergreen
I Wanna Be Yours,Arctic Monkeys,1825413,-80003,13563046,Rock,United Kingdom,71,1354,15388459,Falling,Average,Evergreen
Who,Jimin,1807214,176731,11524586,R&B,South Korea,72,611,13331800,Rising,Average,Evergreen
VOY A LLeVARTE PA PR,Bad Bunny,1780848,-133648,12359622,Latin,Puerto Rico,74,375,14140470,Falling,Average,Evergreen
daño (w/ Tito Double P),Peso Pluma,1780764,34375,11510694,Latin,Mexico,75,86,13291458,Rising,Average,Stable Hit
Starboy (w/ Daft Punk),The Weeknd,1761445,-119116,12541479,R&B,Canada,76,2095,14302924,Falling,Average,Evergreen
Lose Control,Teddy Swims,1737868,29374,11380332,Pop,United States,77,856,13118200,Rising,Average,Evergreen
Riptide,Vance Joy,1737857,-5537,11544093,Rock,Australia,78,2586,13281950,Falling,Average,Evergreen
WILDFLOWER,Billie Eilish,1730195,-201850,13900491,Pop,United States,79,674,15630686,Falling,Average,Evergreen
LA CANCIÓN (w/ Bad Bunny),J Balvin,1708412,3072,11498926,Electronic,Colombia,80,988,13207338,Rising,Average,Evergreen
Qué Pasaría... (w/ Bad Bunny),Rauw Alejandro,1674168,25719,11406360,Latin,Puerto Rico,82,427,13080528,Rising,Average,Evergreen
Feel Good Inc,Gorillaz,1669648,-99808,11921501,Electronic,United Kingdom,83,443,13591149,Falling,Average,Evergreen
All The Stars (w/ SZA),Kendrick Lamar,1665602,-10997,11456499,Hip Hop,United States,84,1016,13122101,Falling,Average,Evergreen
See You Again (w/ Kali Uchis),"Tyler, The Creator",1662229,73090,10586720,Hip Hop,United States,85,1066,12248949,Rising,Average,Evergreen
In the End,Linkin Park,1647656,-111701,11401354,Rock,United States,86,1012,13049010,Falling,Average,Evergreen
"One Of The Girls (w/ JENNIE, Lily-Rose Depp)",The Weeknd,1643774,-137154,12741548,R&B,Canada,87,896,14385322,Falling,Average,Evergreen
Danza Kuduro (w/ Lucenzo),Don Omar,1643700,-105775,10737763,Latin,Puerto Rico,88,802,12381463,Falling,Average,Evergreen
Aperture,Harry Styles,1643576,-159524,13195579,Pop,United Kingdom,89,58,14839155,Falling,Average,Stable Hit
"La Plena - W Sound 05 (w/ Beéle, Ovy On The Drums)",W Sound,1639753,-17075,10668572,Falcom,Japan,90,389,12308325,Falling,Average,Evergreen
"LA VILLA (w/ Kapo, Gangsta)",Ryan Castro,1634806,64909,10801896,Rock,United States,91,75,12436702,Rising,Average,Stable Hit
"Good Luck, Babe!",Chappell Roan,1621060,15852,10803226,Pop,United States,92,710,12424286,Rising,Average,Evergreen
Viva La Vida,Coldplay,1610233,106290,10117917,Rock,United Kingdom,93,1329,11728150,Rising,Average,Evergreen
As It Was,Harry Styles,1608775,-150504,11660629,Pop,United Kingdom,94,1401,13269404,Falling,Average,Evergreen
We Are The People,Empire Of The Sun,1594097,-30037,11149329,Electronic,Australia,95,242,12743426,Falling,Average,Evergreen
The Less I Know The Better,Tame Impala,1593781,-51333,10870662,Rock,Australia,96,510,12464443,Falling,Average,Evergreen
505,Arctic Monkeys,1587695,-113645,11653237,Rock,United Kingdom,97,1537,13240932,Falling,Average,Evergreen
Seven (w/ Latto),Jung Kook,1580746,-80854,11202875,Pop,South Korea,98,981,12783621,Falling,Average,Evergreen
Marlboro Rojo,Fuerza Regida,1564019,112870,10014833,Latin,Mexico,99,317,11578852,Rising,Average,Evergreen
Todo Lo Fue,Lenin Ramírez,1563733,90601,10043908,Latin,Mexico,100,58,11607641,Rising,Average,Stable Hit
The Visitor,Sienna Spiro,1558344,-296012,12044907,R&B,United Kingdom,101,9,13603251,Falling,Average,New
Billie Jean,Michael Jackson,1551069,20972,9991848,Pop,United States,102,363,11542917,Rising,Average,Evergreen
Si Antes Te Hubiera Conocido,Karol G,1540953,46742,9623813,Latin,Colombia,103,583,11164766,Rising,Average,Evergreen
Pvta Luna,Neton Vega,1537690,56324,10293259,Latin,Mexico,104,127,11830949,Rising,Average,Evergreen
Ya Borracho,Herencia De Grandes,1536251,49704,9999127,Latin,Mexico,105,122,11535378,Rising,Average,Evergreen
undressed,sombr,1535615,-88400,10972970,Pop,United States,106,358,12508585,Falling,Average,Evergreen
Shape of You,Ed Sheeran,1532739,-41473,10263688,Pop,United Kingdom,107,2815,11796427,Falling,Average,Evergreen
That’s So True,Gracie Abrams,1526228,-51917,10719195,Pop,United States,108,519,12245423,Falling,Average,Evergreen
Midnight Sun,Zara Larsson,1512185,-10911,10133254,Pop,Sweden,109,63,11645439,Falling,Average,Stable Hit
When I Was Your Man,Bruno Mars,1508958,144568,10366342,Pop,United States,110,1476,11875300,Rising,Average,Evergreen
Have You Ever Seen The Rain,Creedence Clearwater Revival,1507387,52997,9344647,Rock,United States,111,484,10852034,Rising,Average,Evergreen
Sparks,Coldplay,1504857,-3015,10932582,Rock,United Kingdom,112,562,12437439,Falling,Average,Evergreen
COQUETA (w/ Grupo Frontera),Fuerza Regida,1503126,62199,9876432,Latin,Mexico,113,309,11379558,Rising,Average,Evergreen
Somewhere Only We Know,Keane,1496326,10006,10165562,Rock,United Kingdom,114,1193,11661888,Rising,Average,Evergreen
Taste Back,Harry Styles,1480809,-206276,12746602,Rock,United Kingdom,115,16,14227411,Falling,Average,New
Zoo (w/ Shakira),Disney,1466813,189999,4001191,Pop,United States,116,58,5468004,Rising,Average,Stable Hit
Smells Like Teen Spirit - Remastered,Nirvana,1453513,-125183,10271555,Rock,United States,117,727,11725068,Falling,Average,Evergreen
Blinding Lights,The Weeknd,1448450,11224,9729402,R&B,Canada,118,2301,11177852,Rising,Average,Evergreen
7-3 (w/ Tito Double P),Peso Pluma,1440677,5573,9736835,Latin,Mexico,119,86,11177512,Rising,Average,Stable Hit
Porch Light,Noah Kahan,1430611,-374516,12359863,Pop,United States,120,9,13790474,Falling,Average,New
Just the Way You Are,Bruno Mars,1423798,-102703,10482326,Pop,United States,121,1197,11906124,Falling,Average,Evergreen
Coming Up Roses,Harry Styles,1418986,-230104,12650537,Pop,United Kingdom,122,16,14069523,Falling,Average,New
Nice To Each Other,Olivia Dean,1416007,-50721,9872551,Pop,United States,123,212,11288558,Falling,Average,Evergreen
Counting Stars,OneRepublic,1414383,-31879,9525522,Pop,United States,124,2495,10939905,Falling,Average,Evergreen
Fame is a Gun,Addison Rae,1404894,-2613,10047427,Pop,United States,125,120,11452321,Falling,Average,Evergreen
Only Girl (In The World),Rihanna,1398296,-52230,9276305,Pop,United States,126,131,10674601,Falling,Average,Evergreen
Bring Me To Life,Evanescence,1396427,-131213,10205781,Rock,United States,127,341,11602208,Falling,Average,Evergreen
Don't Stop The Music,Rihanna,1395227,-40325,9282714,Pop,United States,128,117,10677941,Falling,Average,Evergreen
Timeless (w/ Playboi Carti),The Weeknd,1392146,-94943,10349253,R&B,Canada,129,541,11741399,Falling,Average,Evergreen
Promiscuous (w/ Timbaland),Nelly Furtado,1390532,-5054,8860680,Pop,Canada,130,171,10251212,Falling,Average,Evergreen
"Give Me Everything (w/ Ne-Yo, AFROJACK, Nayer)",Pitbull,1389531,-110927,9497950,Pop,United States,131,511,10887481,Falling,Average,Evergreen
"chiclona (w/ Tito Double P, LENCHO)",Peso Pluma,1389411,-12742,9202643,Latin,Mexico,132,21,10592054,Falling,Average,New
no tiene sentido,Beéle,1380148,-55381,9480736,Latin,Colombia,133,287,10860884,Falling,Average,Evergreen
Kiss It Better,Rihanna,1379747,-223043,10359276,Pop,United States,134,142,11739023,Falling,Average,Evergreen
Body,Don Toliver,1377373,-100397,10001871,Hip Hop,United States,135,51,11379244,Falling,Average,Stable Hit
The Night We Met,Lord Huron,1368186,-94429,10515041,Rock,United States,137,1327,11883227,Falling,Average,Evergreen
Sweet Child O' Mine,Guns N' Roses,1367839,-13859,8983873,Rock,United States,138,440,10351712,Falling,Average,Evergreen
Let Me Love You (w/ Justin Bieber),DJ Snake,1364636,-88823,10084292,Electronic,France,139,809,11448928,Falling,Average,Evergreen
Numb,Linkin Park,1350782,-120313,9629438,Rock,United States,140,704,10980220,Falling,Average,Evergreen
Africa,TOTO,1350745,-23426,7537107,Rock,United States,141,753,8887852,Falling,Average,Evergreen
Who Knows,Daniel Caesar,1349819,-151500,10486538,R&B,Canada,142,120,11836357,Falling,Average,Evergreen
The Man Who Can't Be Moved,The Script,1349075,-126873,10424946,Rock,United Kingdom,143,157,11774021,Falling,Average,Evergreen
A Couple Minutes,Olivia Dean,1348112,-57009,9770863,Pop,United States,144,118,11118975,Falling,Average,Evergreen
Everybody Wants To Rule The World,Tears For Fears,1345799,28946,6232525,Rock,United Kingdom,145,1027,7578324,Rising,Average,Evergreen
No One Noticed,The Marías,1342468,-53818,10132311,Rock,United Kingdom,146,496,11474779,Falling,Average,Evergreen
Without Me,Eminem,1335886,-100932,9154300,Hip Hop,United States,147,1637,10490186,Falling,Average,Evergreen
Hips Don't Lie (w/ Wyclef Jean),Shakira,1330852,24927,6218904,Pop,Colombia,148,338,7549756,Rising,Average,Evergreen
Me Rehúso,Danny Ocean,1326162,-38797,8914757,Latin,United States,149,617,10240919,Falling,Average,Evergreen
"VeLDÁ (w/ Omar Courtz, Dei V)",Bad Bunny,1326149,-90827,9468025,Latin,Puerto Rico,150,395,10794174,Falling,Average,Evergreen
Style,Taylor Swift,1311077,-73973,8934698,Pop,United States,152,347,10245775,Falling,Average,Evergreen
Payphone (w/ Wiz Khalifa),Maroon 5,1306200,-28788,9226178,Pop,United States,153,712,10532378,Falling,Average,Evergreen
Please Please Please,Sabrina Carpenter,1296957,-1727,5009467,Pop,United States,154,503,6306424,Falling,Average,Evergreen
TU SANCHO,Fuerza Regida,1296297,19803,8708123,Latin,Mexico,155,284,10004420,Rising,Average,Evergreen
Shut up My Moms Calling,Hotel Ugly,1294677,-8737,9158699,R&B,United States,156,773,10453376,Falling,Average,Evergreen
"Ready, Steady, Go!",Harry Styles,1294001,-190275,11338844,Pop,United Kingdom,157,16,12632845,Falling,Average,New
We Found Love (w/ Calvin Harris),Rihanna,1292535,-110188,7904030,Pop,United States,158,823,9196565,Falling,Average,Evergreen
Sex on Fire,Kings of Leon,1290404,5746,3835428,Rock,United States,159,63,5125832,Rising,Average,Stable Hit
Wonderwall - Remastered,Oasis,1286520,-64148,8821556,Rock,United Kingdom,160,884,10108076,Falling,Average,Evergreen
Too Sweet,Hozier,1283948,40456,6149401,Pop,Ireland,161,620,7433349,Rising,Average,Evergreen
"Can't Hold Us (w/ Macklemore, Ryan Lewis, Ray Dalton)",Macklemore & Ryan Lewis,1282248,-87604,8781747,Hip Hop,United States,163,1211,10063995,Falling,Average,Evergreen
DAISIES,Justin Bieber,1281664,-20169,8990092,Pop,Canada,164,252,10271756,Falling,Average,Evergreen
Sunflower - Spider-Man: Into the Spider-Verse (w/ Swae Lee),Post Malone,1281251,-6790,5025791,Pop,United States,165,2292,6307042,Falling,Average,Evergreen
Take on Me - 2015 Remaster,a-ha,1279646,-21334,4937908,Pop,Norway,167,14,6217554,Falling,Average,New
Can't Stop - 2014 Remaster,Red Hot Chili Peppers,1275766,-114450,9103531,Rock,United States,169,20,10379297,Falling,Average,New
Poker Face,Lady Gaga,1275472,-64590,8736190,Pop,United States,170,389,10011662,Falling,Average,Evergreen
Cruel Summer,Taylor Swift,1268541,9198,2527884,Pop,United States,172,1014,3796425,Rising,Average,Evergreen
Boys Don't Cry,The Cure,1263767,15843,6006104,Rock,United Kingdom,173,53,7269871,Rising,Average,Stable Hit
luther,Kendrick Lamar,1260494,-89450,9151667,Hip Hop,United States,175,483,10412161,Falling,Average,Evergreen
What You Saying,Lil Uzi Vert,1259173,-27420,8754899,Hip Hop,United States,176,80,10014072,Falling,Average,Stable Hit
S&M,Rihanna,1257351,-87753,7352626,Pop,United States,177,30,8609977,Falling,Average,New
No Pole,Don Toliver,1254541,-53350,9273774,Hip Hop,United States,178,454,10528315,Falling,Average,Evergreen
Last Friday Night (T.G.I.F.),Katy Perry,1251765,-19664,2523194,Pop,United States,179,99,3774959,Falling,Average,Stable Hit
Just Keep Watching (From F1® The Movie) (w/ F1 The Album),Tate McRae,1245007,-77995,9035434,Pop,Canada,181,270,10280441,Falling,Average,Evergreen
Flashing Lights (w/ Dwele),Kanye West,1241168,-39451,8480893,Pop,United Kingdom,185,244,9722061,Falling,Average,Evergreen
Gangsta's Paradise (w/ L.V.),Coolio,1239884,-37552,4891917,Hip Hop,United States,187,791,6131801,Falling,Average,Evergreen
nuts (w/ rainy bear),Lil Peep,1237223,-11727,4787172,Hip Hop,United States,188,5,6024395,Falling,Average,New
Perfect,Ed Sheeran,1227709,-74196,8956978,Pop,United Kingdom,190,3070,10184687,Falling,Average,Evergreen
Summertime Sadness,Lana Del Rey,1227362,-104470,7508206,Pop,United States,191,1093,8735568,Falling,Average,Evergreen
Come As You Are - Remastered,Nirvana,1224750,-89453,6372663,Rock,United States,192,153,7597413,Falling,Average,Evergreen
Breakin' Dishes,Rihanna,1224675,-24245,8638532,Pop,United States,193,346,9863207,Falling,Average,Evergreen
The Chain - 2004 Remaster,Fleetwood Mac,1210598,-79537,8817306,Rock,United Kingdom,196,205,10027904,Falling,Average,Evergreen
Love On The Brain,Rihanna,1203160,-69820,7439269,R&B,United States,197,352,8642429,Falling,Average,Evergreen
Sign of the Times,Harry Styles,1198929,-121566,3816744,Pop,United Kingdom,198,331,5015673,Falling,Average,Evergreen
Sorry,Justin Bieber,1192146,-86760,7346804,Pop,Canada,199,767,8538950,Falling,Average,Evergreen